import json

# Vocabulary transcribed directly from the uploaded "Japanese Picture
# Dictionary" (Timothy G. Stout, Tuttle) by viewing rasterized page
# images — the PDF's Japanese text uses a non-standard CID font
# encoding that even poppler's Adobe-Japan1 CMap resource can't
# decode, so bulk text extraction was not possible; every entry below
# was read directly off the page images chapter by chapter.
#
# (word, reading, romaji, meaning, category)
PICTURE_DICT = [

 # ---------------------------------------------------------- shapes --
 ("四角形", "しかっけい", "shikakkei", "rectangle", "Shapes & Sizes"),
 ("円形", "えんけい", "enkei", "circle", "Shapes & Sizes"),
 ("八角形", "はっかっけい", "hakkakkei", "octagon", "Shapes & Sizes"),
 ("五角形", "ごかっけい", "gokakkei", "pentagon", "Shapes & Sizes"),
 ("正方形", "せいほうけい", "seihōkei", "square", "Shapes & Sizes"),
 ("ハート型", "はーとがた", "hātogata", "heart shape", "Shapes & Sizes"),
 ("だ円形", "だえんけい", "daenkei", "oval", "Shapes & Sizes"),
 ("星型", "ほしがた", "hoshigata", "star shape", "Shapes & Sizes"),
 ("三角形", "さんかっけい", "sankakkei", "triangle", "Shapes & Sizes"),
 ("六角形", "ろっかっけい", "rokkakkei", "hexagon", "Shapes & Sizes"),
 ("ひし形", "ひしがた", "hishigata", "diamond shape", "Shapes & Sizes"),
 ("形", "かたち", "katachi", "shape", "Shapes & Sizes"),
 ("大きさ", "おおきさ", "ōkisa", "size", "Shapes & Sizes"),
 ("もっと大きい", "もっとおおきい", "motto ōkii", "larger", "Shapes & Sizes"),
 ("もっと小さい", "もっとちいさい", "motto chiisai", "smaller", "Shapes & Sizes"),
 ("金色", "きんいろ", "kin'iro", "gold (color)", "Colors"),
 ("銀色", "ぎんいろ", "gin'iro", "silver (color)", "Colors"),
 ("濃い", "こい", "koi", "dark (color)", "Colors"),
 ("薄い", "うすい", "usui", "light (color)", "Colors"),

 # -------------------------------------------------------- opposites --
 ("上", "うえ", "ue", "up (opposite of 下 shita, down)", "Opposites"),
 ("下", "した", "shita", "down (opposite of 上 ue, up)", "Opposites"),
 ("受ける", "うける", "ukeru", "to receive (opposite of あげる, to give)", "Opposites"),
 ("あげる", "あげる", "ageru", "to give (opposite of 受ける ukeru, to receive)", "Opposites"),
 ("たくさん", "たくさん", "takusan", "many (opposite of 少し sukoshi, few)", "Opposites"),
 ("少し", "すこし", "sukoshi", "few, a little (opposite of たくさん takusan, many)", "Opposites"),
 ("背が高い", "せがたかい", "se ga takai", "tall (opposite of 背が低い se ga hikui, short)", "Opposites"),
 ("背が低い", "せがひくい", "se ga hikui", "short (height, opposite of 背が高い se ga takai, tall)", "Opposites"),
 ("古い", "ふるい", "furui", "old (things, opposite of 新しい atarashii, new)", "Opposites"),
 ("新しい", "あたらしい", "atarashii", "new (opposite of 古い furui, old)", "Opposites"),
 ("出る", "でる", "deru", "to exit (opposite of 入る hairu, to enter)", "Opposites"),
 ("入る", "はいる", "hairu", "to enter (opposite of 出る deru, to exit)", "Opposites"),
 ("良い", "よい", "yoi", "good (opposite of 悪い warui, bad)", "Opposites"),
 ("悪い", "わるい", "warui", "bad (opposite of 良い yoi, good)", "Opposites"),
 ("忙しい", "いそがしい", "isogashii", "busy (opposite of 暇 hima, idle)", "Opposites"),
 ("暇", "ひま", "hima", "idle, free time (opposite of 忙しい isogashii, busy)", "Opposites"),
 ("長い", "ながい", "nagai", "long (opposite of 短い mijikai, short)", "Opposites"),
 ("短い", "みじかい", "mijikai", "short (length, opposite of 長い nagai, long)", "Opposites"),
 ("年をとっています", "としをとっています", "toshi o totte imasu", "old (age, opposite of 若い wakai, young)", "Opposites"),
 ("若い", "わかい", "wakai", "young (opposite of 年をとっています, old)", "Opposites"),
 ("大きい", "おおきい", "ōkii", "big (opposite of 小さい chiisai, small)", "Opposites"),
 ("小さい", "ちいさい", "chiisai", "small (opposite of 大きい ōkii, big)", "Opposites"),
 ("開ける", "あける", "akeru", "to open (opposite of 閉める shimeru, to close)", "Opposites"),
 ("閉める", "しめる", "shimeru", "to close (opposite of 開ける akeru, to open)", "Opposites"),
 ("太っています", "ふとっています", "futotte imasu", "fat (opposite of 痩せています yasete imasu, thin)", "Opposites"),
 ("痩せています", "やせています", "yasete imasu", "thin (opposite of 太っています futotte imasu, fat)", "Opposites"),
 ("着る", "きる", "kiru", "to put on (clothes, opposite of 脱ぐ nugu, to take off)", "Opposites"),
 ("脱ぐ", "ぬぐ", "nugu", "to take off (clothes, opposite of 着る kiru, to put on)", "Opposites"),
 ("難しい", "むずかしい", "muzukashii", "difficult (opposite of 優しい yasashii, easy)", "Opposites"),
 ("優しい", "やさしい", "yasashii", "easy, kind (opposite of 難しい muzukashii, difficult)", "Opposites"),
 ("ある", "ある", "aru", "to have, there is (opposite of ない nai)", "Opposites"),
 ("ない", "ない", "nai", "to not have, there isn't (opposite of ある aru)", "Opposites"),
 ("来る", "くる", "kuru", "to come (opposite of 行く iku, to go)", "Opposites"),
 ("行く", "いく", "iku", "to go (opposite of 来る kuru, to come)", "Opposites"),
 ("着く", "つく", "tsuku", "to arrive (opposite of 出かける dekakeru, to leave)", "Opposites"),
 ("出かける", "でかける", "dekakeru", "to leave, go out (opposite of 着く tsuku, to arrive)", "Opposites"),
 ("中", "なか", "naka", "inside (opposite of 外 soto, outside)", "Opposites"),
 ("外", "そと", "soto", "outside (opposite of 中 naka, inside)", "Opposites"),
 ("前", "まえ", "mae", "in front (opposite of 後ろ ushiro, behind)", "Opposites"),
 ("後ろ", "うしろ", "ushiro", "behind (opposite of 前 mae, in front)", "Opposites"),
 ("お腹がいっぱいです", "おなかがいっぱいです", "onaka ga ippai desu", "full (stomach, opposite of お腹が空いています, hungry)", "Opposites"),
 ("お腹が空いています", "おなかがすいています", "onaka ga suite imasu", "hungry (opposite of お腹がいっぱいです, full)", "Opposites"),
 ("覚える", "おぼえる", "oboeru", "to remember (opposite of 忘れる wasureru, to forget)", "Opposites"),
 ("始まる", "はじまる", "hajimaru", "to begin (opposite of 終わる owaru, to end)", "Opposites"),
 ("終わる", "おわる", "owaru", "to end (opposite of 始まる hajimaru, to begin)", "Opposites"),
 ("近い", "ちかい", "chikai", "near (opposite of 遠い tōi, far)", "Opposites"),
 ("遠い", "とおい", "tōi", "far (opposite of 近い chikai, near)", "Opposites"),
 ("違う", "ちがう", "chigau", "wrong (opposite of 正しい tadashii, right)", "Opposites"),
 ("正しい", "ただしい", "tadashii", "right, correct (opposite of 違う chigau, wrong)", "Opposites"),
 ("本物", "ほんもの", "honmono", "real (opposite of 偽物 nisemono, fake)", "Opposites"),
 ("偽物", "にせもの", "nisemono", "fake (opposite of 本物 honmono, real)", "Opposites"),
 ("速い", "はやい", "hayai", "fast (opposite of 遅い osoi, slow)", "Opposites"),
 ("遅い", "おそい", "osoi", "slow (opposite of 速い hayai, fast)", "Opposites"),
 ("高い", "たかい", "takai", "high, expensive (opposite of 低い hikui, low)", "Opposites"),
 ("低い", "ひくい", "hikui", "low (opposite of 高い takai, high)", "Opposites"),
 ("借りる", "かりる", "kariru", "to borrow (opposite of 貸す kasu, to lend)", "Opposites"),
 ("貸す", "かす", "kasu", "to lend (opposite of 借りる kariru, to borrow)", "Opposites"),
 ("悲しい", "かなしい", "kanashii", "sad (opposite of 嬉しい ureshii, happy)", "Opposites"),
 ("嬉しい", "うれしい", "ureshii", "happy (opposite of 悲しい kanashii, sad)", "Opposites"),

 # ------------------------------------------------------------ money --
 ("円", "えん", "en", "yen (Japanese currency)", "Money & Shopping"),
 ("紙幣", "しへい", "shihei", "paper money", "Money & Shopping"),
 ("硬貨", "こうか", "kōka", "coins", "Money & Shopping"),
 ("一円", "いちえん", "ichi en", "one yen", "Money & Shopping"),
 ("五円", "ごえん", "go en", "five yen", "Money & Shopping"),
 ("五十円", "ごじゅうえん", "gojū en", "fifty yen", "Money & Shopping"),
 ("百円", "ひゃくえん", "hyaku en", "one hundred yen", "Money & Shopping"),
 ("五百円", "ごひゃくえん", "gohyaku en", "five hundred yen", "Money & Shopping"),
 ("千円", "せんえん", "sen en", "one thousand yen", "Money & Shopping"),
 ("五千円", "ごせんえん", "gosen en", "five thousand yen", "Money & Shopping"),
 ("一万円", "いちまんえん", "ichiman en", "ten thousand yen", "Money & Shopping"),
 ("小切手", "こぎって", "kogitte", "check", "Money & Shopping"),
 ("小銭", "こぜに", "kozeni", "small change", "Money & Shopping"),
 ("クレジットカード", "くれじっとかーど", "kurejitto kādo", "credit card", "Money & Shopping"),
 ("貯金", "ちょきん", "chokin", "savings", "Money & Shopping"),
 ("為替", "かわせ", "kawase", "currency exchange", "Money & Shopping"),
 ("引き出す", "ひきだす", "hikidasu", "to withdraw money", "Money & Shopping"),
 ("お金", "おかね", "okane", "money", "Money & Shopping"),
 ("値段", "ねだん", "nedan", "price", "Money & Shopping"),
 ("割引", "わりびき", "waribiki", "discount", "Money & Shopping"),
 ("安い", "やすい", "yasui", "cheap", "Money & Shopping"),
 ("高い", "たかい", "takai", "expensive", "Money & Shopping"),
 ("利子", "りし", "rishi", "interest", "Money & Shopping"),
 ("ローン", "ろーん", "rōn", "loan, credit", "Money & Shopping"),
 ("借金", "しゃっきん", "shakkin", "debt", "Money & Shopping"),
 ("預金", "よきん", "yokin", "bank deposit", "Money & Shopping"),
 ("口座番号", "こうざばんごう", "kōza bangō", "account number", "Money & Shopping"),
 ("領収書", "りょうしゅうしょ", "ryōshūsho", "receipt", "Money & Shopping"),
 ("掛け金", "かけきん", "kakekin", "installment payment", "Money & Shopping"),
 ("税金", "ぜいきん", "zeikin", "tax", "Money & Shopping"),
 ("現金", "げんきん", "genkin", "cash", "Money & Shopping"),
 ("Sサイズ", "えすさいず", "esu saizu", "S size (clothing)", "Money & Shopping"),
 ("Mサイズ", "えむさいず", "emu saizu", "M size (clothing)", "Money & Shopping"),
 ("Lサイズ", "えるさいず", "eru saizu", "L size (clothing)", "Money & Shopping"),

 # --------------------------------------------------------- seasons --
 ("春", "はる", "haru", "spring", "Seasons & Holidays"),
 ("夏", "なつ", "natsu", "summer", "Seasons & Holidays"),
 ("秋", "あき", "aki", "autumn, fall", "Seasons & Holidays"),
 ("冬", "ふゆ", "fuyu", "winter", "Seasons & Holidays"),
 ("暖かい", "あたたかい", "atatakai", "warm", "Seasons & Holidays"),
 ("そよ風", "そよかぜ", "soyokaze", "a gentle breeze", "Seasons & Holidays"),
 ("桃の花", "もものはな", "momo no hana", "peach blossoms", "Seasons & Holidays"),
 ("咲く", "さく", "saku", "to flower, to bloom", "Seasons & Holidays"),
 ("小雨", "こさめ", "kosame", "drizzle", "Seasons & Holidays"),
 ("日傘", "ひがさ", "higasa", "sunshade, parasol", "Seasons & Holidays"),
 ("水遊び", "みずあそび", "mizuasobi", "water play", "Seasons & Holidays"),
 ("雪だるまを作る", "ゆきだるまをつくる", "yukidaruma o tsukuru", "to make a snowman", "Seasons & Holidays"),
 ("収穫", "しゅうかく", "shūkaku", "harvest", "Seasons & Holidays"),
 ("扇子", "せんす", "sensu", "folding fan", "Seasons & Holidays"),
 ("雪合戦", "ゆきがっせん", "yukigassen", "snowball fight", "Seasons & Holidays"),
 ("日焼け止め", "ひやけどめ", "hiyakedome", "sunblock lotion", "Seasons & Holidays"),
 ("作物", "さくもつ", "sakumotsu", "crops", "Seasons & Holidays"),
 ("四季", "しき", "shiki", "four seasons", "Seasons & Holidays"),

 # -------------------------------------------------------- holidays --
 ("祝日", "しゅくじつ", "shukujitsu", "festival, holiday", "Seasons & Holidays"),
 ("新年", "しんねん", "shinnen", "New Year", "Seasons & Holidays"),
 ("花火", "はなび", "hanabi", "fireworks", "Seasons & Holidays"),
 ("成人の日", "せいじんのひ", "seijin no hi", "Coming of Age Day", "Seasons & Holidays"),
 ("節分", "せつぶん", "setsubun", "beginning of spring festival", "Seasons & Holidays"),
 ("子供の日", "こどものひ", "kodomo no hi", "Children's Day", "Seasons & Holidays"),
 ("七夕", "たなばた", "Tanabata", "Star Festival", "Seasons & Holidays"),
 ("体育の日", "たいいくのひ", "taiiku no hi", "Health and Sports Day", "Seasons & Holidays"),
 ("運動会", "うんどうかい", "undōkai", "sports day event", "Seasons & Holidays"),
 ("文化の日", "ぶんかのひ", "bunka no hi", "Culture Day", "Seasons & Holidays"),
 ("お餅", "おもち", "omochi", "sticky rice cake", "Seasons & Holidays"),
 ("和菓子", "わがし", "wagashi", "Japanese traditional cakes", "Seasons & Holidays"),
 ("父の日", "ちちのひ", "Chichi no hi", "Father's Day", "Seasons & Holidays"),
 ("母の日", "はははのひ", "Haha no hi", "Mother's Day", "Seasons & Holidays"),
 ("バレンタインデー", "ばれんたいんでー", "Barentain dē", "Valentine's Day", "Seasons & Holidays"),
 ("チョコレート", "ちょこれーと", "chokorēto", "chocolates", "Seasons & Holidays"),
 ("バラ", "ばら", "bara", "roses", "Seasons & Holidays"),
 ("感謝祭", "かんしゃさい", "Kanshasai", "Thanksgiving", "Seasons & Holidays"),
 ("ハロウィーン", "はろうぃーん", "Harowiin", "Halloween", "Seasons & Holidays"),
 ("復活祭", "ふっかつさい", "Fukkatsusai", "Easter", "Seasons & Holidays"),
 ("憲法記念日", "けんぽうきねんび", "Kenpō Kinenbi", "Constitution Day", "Seasons & Holidays"),
 ("誕生日", "たんじょうび", "tanjōbi", "birthday", "Seasons & Holidays"),
 ("夏休み", "なつやすみ", "natsuyasumi", "summer vacation", "Seasons & Holidays"),
 ("冬休み", "ふゆやすみ", "fuyuyasumi", "winter vacation", "Seasons & Holidays"),
 ("記念日", "きねんび", "kinenbi", "anniversary", "Seasons & Holidays"),
 ("周年", "しゅうねん", "shūnen", "anniversary (of years)", "Seasons & Holidays"),
 ("ゴールデンウィーク", "ごーるでんうぃーく", "Gōruden wiiku", "Golden Week", "Seasons & Holidays"),
 ("贈り物", "おくりもの", "okurimono", "gift", "Seasons & Holidays"),
 ("クリスマス", "くりすます", "Kurisumasu", "Christmas", "Seasons & Holidays"),
 ("サンタクロース", "さんたくろーす", "Santakurōsu", "Santa Claus", "Seasons & Holidays"),
 ("ホワイトデー", "ほわいとでー", "Howaitodē", "White Day", "Seasons & Holidays"),
 ("ひな祭り", "ひなまつり", "Hinamatsuri", "Doll Festival", "Seasons & Holidays"),
 ("天皇誕生日", "てんのうたんじょうび", "Tennō tanjōbi", "Emperor's Birthday", "Seasons & Holidays"),

 # -------------------------------------------------------------- school --
 ("試験", "しけん", "shiken", "exam", "School & Learning"),
 ("数学", "すうがく", "sūgaku", "mathematics", "School & Learning"),
 ("体育", "たいいく", "taiiku", "physical education", "School & Learning"),
 ("辞書", "じしょ", "jisho", "dictionary", "School & Learning"),
 ("ホワイトボード", "ほわいとぼーど", "howaitobōdo", "whiteboard", "School & Learning"),
 ("黒板", "こくばん", "kokuban", "blackboard", "School & Learning"),
 ("図書館", "としょかん", "toshokan", "library", "School & Learning"),
 ("教室", "きょうしつ", "kyōshitsu", "classroom", "School & Learning"),
 ("先生", "せんせい", "sensei", "teacher", "School & Learning"),
 ("コピー機", "こぴーき", "kopiiki", "photocopier", "School & Learning"),
 ("手をあげる", "てをあげる", "te o ageru", "to raise your hand", "School & Learning"),
 ("計算機", "けいさんき", "keisanki", "calculator", "School & Learning"),
 ("科学", "かがく", "kagaku", "science", "School & Learning"),
 ("教授", "きょうじゅ", "kyōju", "professor", "School & Learning"),
 ("講義室", "こうぎしつ", "kōgishitsu", "lecture hall", "School & Learning"),
 ("生徒", "せいと", "seito", "student", "School & Learning"),
 ("クラスメート", "くらすめーと", "kurasumēto", "classmate", "School & Learning"),
 ("宿題", "しゅくだい", "shukudai", "homework", "School & Learning"),

 # ----------------------------------------------------------- counters --
 ("一つ", "ひとつ", "hitotsu", "counter for general objects (hitotsu, futatsu, mittsu...)", "Counters"),
 ("一人", "ひとり", "hitori", "counter for people (hitori, futari, sannin...)", "Counters"),
 ("一枚", "いちまい", "ichimai", "counter for thin flat objects — paper, shirts, tickets (ichimai, nimai...)", "Counters"),
 ("一本", "いっぽん", "ippon", "counter for long cylindrical objects — pencils, trees (ippon, nihon...)", "Counters"),
 ("一台", "いちだい", "ichidai", "counter for machines — cars, computers (ichidai, nidai...)", "Counters"),
 ("一杯", "いっぱい", "ippai", "counter for cups and glasses of drink (ippai, nihai...)", "Counters"),
 ("一匹", "いっぴき", "ippiki", "counter for small animals (ippiki, nihiki...)", "Counters"),
 ("一頭", "いっとう", "ittō", "counter for large animals (ittō, nitō...)", "Counters"),
 ("一個", "いっこ", "ikko", "counter for small or round objects (ikko, niko...)", "Counters"),
 ("一冊", "いっさつ", "issatsu", "counter for books and notebooks (issatsu, nisatsu...)", "Counters"),

 # ---------------------------------------------------------- numbers --
 ("十一", "じゅういち", "jūichi", "eleven", "Numbers & Counting"),
 ("十二", "じゅうに", "jūni", "twelve", "Numbers & Counting"),
 ("二十", "にじゅう", "nijū", "twenty", "Numbers & Counting"),
 ("三十", "さんじゅう", "sanjū", "thirty", "Numbers & Counting"),
 ("四十", "よんじゅう", "yonjū", "forty", "Numbers & Counting"),
 ("五十", "ごじゅう", "gojū", "fifty", "Numbers & Counting"),
 ("六十", "ろくじゅう", "rokujū", "sixty", "Numbers & Counting"),
 ("七十", "ななじゅう", "nanajū", "seventy", "Numbers & Counting"),
 ("八十", "はちじゅう", "hachijū", "eighty", "Numbers & Counting"),
 ("九十", "きゅうじゅう", "kyūjū", "ninety", "Numbers & Counting"),
 ("十万", "じゅうまん", "jūman", "one hundred thousand", "Numbers & Counting"),
 ("百万", "ひゃくまん", "hyakuman", "one million", "Numbers & Counting"),
 ("一億", "いちおく", "ichioku", "one hundred million", "Numbers & Counting"),
 ("十億", "じゅうおく", "jūoku", "one billion", "Numbers & Counting"),
 ("半分", "はんぶん", "hanbun", "one half", "Numbers & Counting"),
 ("四分の一", "よんぶんのいち", "yonbun no ichi", "one quarter", "Numbers & Counting"),
 ("四分の三", "よんぶんのさん", "yonbun no san", "three quarters", "Numbers & Counting"),
 ("三分の一", "さんぶんのいち", "sanbun no ichi", "one third", "Numbers & Counting"),
 ("三分の二", "さんぶんのに", "sanbun no ni", "two thirds", "Numbers & Counting"),
 ("割る", "わる", "waru", "to divide", "Numbers & Counting"),
 ("掛ける", "かける", "kakeru", "to multiply", "Numbers & Counting"),
 ("引く", "ひく", "hiku", "to subtract", "Numbers & Counting"),
 ("足す", "たす", "tasu", "to add", "Numbers & Counting"),
 ("足し算", "たしざん", "tashizan", "addition", "Numbers & Counting"),
 ("引き算", "ひきざん", "hikizan", "subtraction", "Numbers & Counting"),
 ("掛け算", "かけざん", "kakezan", "multiplication", "Numbers & Counting"),
 ("割り算", "わりざん", "warizan", "division", "Numbers & Counting"),
 ("偶数", "ぐうすう", "gūsū", "even numbers", "Numbers & Counting"),
 ("奇数", "きすう", "kisū", "odd numbers", "Numbers & Counting"),
 ("第一", "だいいち", "dai-ichi", "first (ordinal)", "Numbers & Counting"),
 ("第二", "だいに", "dai-ni", "second (ordinal)", "Numbers & Counting"),
 ("第三", "だいさん", "dai-san", "third (ordinal)", "Numbers & Counting"),

 # ------------------------------------------------------- work & jobs --
 ("弁護士", "べんごし", "bengoshi", "lawyer", "Work & Jobs"),
 ("裁判官", "さいばんかん", "saibankan", "judge", "Work & Jobs"),
 ("投資家", "とうしか", "tōshika", "financier", "Work & Jobs"),
 ("エンジニア", "えんじにあ", "enjinia", "engineer", "Work & Jobs"),
 ("会計士", "かいけいし", "kaikeishi", "accountant", "Work & Jobs"),
 ("薬剤師", "やくざいし", "yakuzaishi", "pharmacist", "Work & Jobs"),
 ("芸術家", "げいじゅつか", "geijutsuka", "artist", "Work & Jobs"),
 ("音楽家", "おんがくか", "ongakuka", "musician", "Work & Jobs"),
 ("建築家", "けんちくか", "kenchikuka", "architect", "Work & Jobs"),
 ("事務所", "じむしょ", "jimusho", "office", "Work & Jobs"),
 ("管理職", "かんりしょく", "kanrishoku", "manager", "Work & Jobs"),
 ("秘書", "ひしょ", "hisho", "secretary", "Work & Jobs"),
 ("シェフ", "しぇふ", "shefu", "chef", "Work & Jobs"),
 ("写真家", "しゃしんか", "shashinka", "photographer", "Work & Jobs"),
 ("パイロット", "ぱいろっと", "pairotto", "pilot", "Work & Jobs"),
 ("歯医者", "はいしゃ", "haisha", "dentist", "Work & Jobs"),
 ("消防士", "しょうぼうし", "shōbōshi", "firefighter", "Work & Jobs"),
 ("農家", "のうか", "nōka", "farmer", "Work & Jobs"),
 ("会社", "かいしゃ", "kaisha", "company", "Work & Jobs"),
 ("企業家", "きぎょうか", "kigyōka", "entrepreneur", "Work & Jobs"),
 ("調べる", "しらべる", "shiraberu", "to inspect", "Work & Jobs"),
 ("出勤する", "しゅっきんする", "shukkin suru", "to go to work", "Work & Jobs"),
 ("同僚", "どうりょう", "dōryō", "colleague", "Work & Jobs"),
 ("仕事", "しごと", "shigoto", "work, job", "Work & Jobs"),
 ("職員", "しょくいん", "shokuin", "staff, personnel", "Work & Jobs"),
 ("見習い", "みならい", "minarai", "apprentice", "Work & Jobs"),
 ("インターン", "いんたーん", "intān", "intern", "Work & Jobs"),
 ("アルバイト", "あるばいと", "arubaito", "part-time job", "Work & Jobs"),
 ("残業する", "ざんぎょうする", "zangyō suru", "to work overtime", "Work & Jobs"),
 ("方法", "ほうほう", "hōhō", "method", "Work & Jobs"),
 ("機会", "きかい", "kikai", "opportunity", "Work & Jobs"),

 # --------------------------------------------------------------- health --
 ("病院", "びょういん", "byōin", "hospital", "Health & Body"),
 ("看護師", "かんごし", "kangoshi", "nurse", "Health & Body"),
 ("医者", "いしゃ", "isha", "doctor", "Health & Body"),
 ("患者", "かんじゃ", "kanja", "patient", "Health & Body"),
 ("血液検査", "けつえきけんさ", "ketsueki kensa", "blood test", "Health & Body"),
 ("血圧", "けつあつ", "ketsuatsu", "blood pressure", "Health & Body"),
 ("風邪をひく", "かぜをひく", "kaze o hiku", "to catch a cold", "Health & Body"),
 ("咳が出る", "せきがでる", "seki ga deru", "to cough", "Health & Body"),
 ("熱", "ねつ", "netsu", "fever", "Health & Body"),
 ("病気になる", "びょうきになる", "byōki ni naru", "to fall sick", "Health & Body"),
 ("薬を飲む", "くすりをのむ", "kusuri o nomu", "to take medicine", "Health & Body"),
 ("薬", "くすり", "kusuri", "medicine", "Health & Body"),
 ("錠剤", "じょうざい", "jōzai", "pills", "Health & Body"),
 ("注射", "ちゅうしゃ", "chūsha", "injection", "Health & Body"),
 ("頭", "あたま", "atama", "head", "Health & Body"),
 ("首", "くび", "kubi", "neck", "Health & Body"),
 ("頬", "ほほ", "hoho", "cheek", "Health & Body"),
 ("顔", "かお", "kao", "face", "Health & Body"),
 ("眉毛", "まゆげ", "mayuge", "eyebrow", "Health & Body"),
 ("舌", "した", "shita", "tongue", "Health & Body"),
 ("歯", "は", "ha", "teeth", "Health & Body"),
 ("顎", "あご", "ago", "chin", "Health & Body"),
 ("唇", "くちびる", "kuchibiru", "lips", "Health & Body"),
 ("指", "ゆび", "yubi", "fingers", "Health & Body"),
 ("足指", "あしゆび", "ashiyubi", "toes", "Health & Body"),
 ("額", "ひたい", "hitai", "forehead", "Health & Body"),
 ("肩", "かた", "kata", "shoulder", "Health & Body"),
 ("筋肉", "きんにく", "kinniku", "muscles", "Health & Body"),
 ("胸", "むね", "mune", "chest", "Health & Body"),
 ("腹", "はら", "hara", "abdomen", "Health & Body"),
 ("腕", "うで", "ude", "arm", "Health & Body"),
 ("肘", "ひじ", "hiji", "elbow", "Health & Body"),
 ("腿", "もも", "momo", "thigh", "Health & Body"),
 ("膝", "ひざ", "hiza", "knee", "Health & Body"),
 ("脚", "あし", "ashi", "leg", "Health & Body"),
 ("足首", "あしくび", "ashikubi", "ankle", "Health & Body"),
 ("臓器", "ぞうき", "zōki", "organs", "Health & Body"),
 ("皮膚", "ひふ", "hifu", "skin", "Health & Body"),
 ("血液", "けつえき", "ketsueki", "blood", "Health & Body"),
 ("血管", "けっかん", "kekkan", "blood vessels", "Health & Body"),
 ("骨", "ほね", "hone", "bone", "Health & Body"),
 ("健康", "けんこう", "kenkō", "health", "Health & Body"),
 ("胃", "い", "i", "stomach", "Health & Body"),
 ("脳", "のう", "nō", "brain", "Health & Body"),
 ("肺", "はい", "hai", "lungs", "Health & Body"),
 ("心臓", "しんぞう", "shinzō", "heart (organ)", "Health & Body"),
 ("腎臓", "じんぞう", "jinzō", "kidneys", "Health & Body"),
 ("腸", "ちょう", "chō", "intestines", "Health & Body"),
 ("肝臓", "かんぞう", "kanzō", "liver", "Health & Body"),

 # ---------------------------------------------------------- environment --
 ("庭", "にわ", "niwa", "garden", "Environment & Nature"),
 ("公園", "こうえん", "kōen", "park", "Environment & Nature"),
 ("公害", "こうがい", "kōgai", "pollution", "Environment & Nature"),
 ("草", "くさ", "kusa", "grass", "Environment & Nature"),
 ("電気自動車", "でんきじどうしゃ", "denki jidōsha", "electric car", "Environment & Nature"),
 ("海", "うみ", "umi", "ocean", "Environment & Nature"),
 ("川", "かわ", "kawa", "river", "Environment & Nature"),
 ("太陽エネルギー", "たいようえねるぎー", "taiyō enerugii", "solar energy", "Environment & Nature"),
 ("静か", "しずか", "shizuka", "quiet", "Environment & Nature"),
 ("空気", "くうき", "kūki", "air", "Environment & Nature"),
 ("風力", "ふうりょく", "fūryoku", "wind power", "Environment & Nature"),

 # -------------------------------------------------------------- animals --
 ("動物園", "どうぶつえん", "dōbutsuen", "zoo", "Animals"),
 ("シマウマ", "しまうま", "shimauma", "zebra", "Animals"),
 ("ゴリラ", "ごりら", "gorira", "gorilla", "Animals"),
 ("恐竜", "きょうりゅう", "kyōryū", "dinosaur", "Animals"),
 ("ヤギ", "やぎ", "yagi", "goat", "Animals"),
 ("羊", "ひつじ", "hitsuji", "sheep", "Animals"),
 ("オオカミ", "おおかみ", "ōkami", "wolf", "Animals"),
 ("蛇", "へび", "hebi", "snake", "Animals"),
 ("孔雀", "くじゃく", "kujaku", "peacock", "Animals"),
 ("鶏", "にわとり", "niwatori", "chicken", "Animals"),
 ("鳥", "とり", "tori", "bird", "Animals"),
 ("竜", "りゅう", "ryū", "dragon", "Animals"),
 ("蚊", "か", "ka", "mosquito", "Animals"),
 ("ハエ", "はえ", "hae", "housefly", "Animals"),
 ("蜂", "はち", "hachi", "bee", "Animals"),
 ("蝶", "ちょう", "chō", "butterfly", "Animals"),

 # -------------------------------------------------------- sports & fitness --
 ("卓球", "たっきゅう", "takkyū", "table tennis", "Sports & Fitness"),
 ("ラグビー", "らぐびー", "ragubii", "rugby", "Sports & Fitness"),
 ("山登り", "やまのぼり", "yamanobori", "mountain climbing", "Sports & Fitness"),
 ("バドミントン", "ばどみんとん", "badominton", "badminton", "Sports & Fitness"),
 ("運動する", "うんどうする", "undō suru", "to exercise", "Sports & Fitness"),
 ("ランニング", "らんにんぐ", "ranningu", "running", "Sports & Fitness"),
 ("長距離走", "ちょうきょりそう", "chōkyorisō", "long-distance running", "Sports & Fitness"),
 ("短距離走", "たんきょりそう", "tankyorisō", "sprint", "Sports & Fitness"),
 ("自転車に乗る", "じてんしゃにのる", "jitensha ni noru", "to cycle", "Sports & Fitness"),
 ("競技会", "きょうぎかい", "kyōgikai", "competition", "Sports & Fitness"),
 ("ゴール", "goーru", "gōru", "finish line, goal", "Sports & Fitness"),
 ("ボート競技", "ぼーときょうぎ", "bōto kyōgi", "rowing", "Sports & Fitness"),
 ("水泳", "すいえい", "suiei", "swimming", "Sports & Fitness"),
 ("バレーボール", "ばれーぼーる", "barēbōru", "volleyball", "Sports & Fitness"),
 ("歩く", "あるく", "aruku", "to walk", "Sports & Fitness"),
 ("ゴルフ", "ごるふ", "gorufu", "golf", "Sports & Fitness"),
 ("アイススケート", "あいすすけーと", "aisu sukēto", "ice-skating", "Sports & Fitness"),
 ("スキー", "すきー", "sukii", "skiing", "Sports & Fitness"),
 ("スニーカー", "すにーかー", "suniikā", "sneakers", "Sports & Fitness"),
 ("テニス", "てにす", "tenisu", "tennis", "Sports & Fitness"),
 ("ラケット", "らけっと", "raketto", "racket", "Sports & Fitness"),
 ("バスケットボール", "ばすけっとぼーる", "basukettobōru", "basketball", "Sports & Fitness"),

 # -------------------------------------------------------------- travel --
 ("ホテル", "ほてる", "hoteru", "hotel", "Travel"),
 ("地図", "ちず", "chizu", "map", "Travel"),
 ("旅行者", "りょこうしゃ", "ryokōsha", "traveler", "Travel"),
 ("荷物", "にもつ", "nimotsu", "luggage", "Travel"),
 ("スーツケース", "すーつけーす", "sūtsukēsu", "suitcase", "Travel"),
 ("ガイド", "がいど", "gaido", "tour guide", "Travel"),
 ("観光地", "かんこうち", "kankōchi", "tourist attraction", "Travel"),
 ("パスポート", "ぱすぽーと", "pasupōto", "passport", "Travel"),
 ("搭乗券", "とうじょうけん", "tōjōken", "boarding pass", "Travel"),
 ("客船", "きゃくせん", "kyakusen", "cruise ship", "Travel"),
 ("土産物店", "みやげものてん", "miyagemonoten", "souvenir shop", "Travel"),
 ("カメラ", "かめら", "kamera", "camera", "Travel"),
 ("写真", "しゃしん", "shashin", "photograph", "Travel"),

 # ------------------------------------------------------------ countries --
 ("タイ", "たい", "Tai", "Thailand", "Countries"),
 ("ミャンマー", "みゃんまー", "Myanmā", "Myanmar", "Countries"),
 ("ベトナム", "べとなむ", "Betonamu", "Vietnam", "Countries"),
 ("フィリピン", "ふぃりぴん", "Firipin", "Philippines", "Countries"),
 ("ラオス", "らおす", "Raosu", "Laos", "Countries"),
 ("カンボジア", "かんぼじあ", "Kanbojia", "Cambodia", "Countries"),
 ("マレーシア", "まれーしあ", "Marēshia", "Malaysia", "Countries"),
 ("ブルネイ", "ぶるねい", "Burunei", "Brunei", "Countries"),
 ("シンガポール", "しんがぽーる", "Shingapōru", "Singapore", "Countries"),
 ("インドネシア", "いんどねしあ", "Indoneshia", "Indonesia", "Countries"),
 ("北アメリカ", "きたあめりか", "Kita Amerika", "North America", "Countries"),
 ("南アメリカ", "みなみあめりか", "Minami Amerika", "South America", "Countries"),
 ("ヨーロッパ", "よーろっぱ", "Yōroppa", "Europe", "Countries"),
 ("アフリカ", "あふりか", "Afurika", "Africa", "Countries"),
 ("アジア", "あじあ", "Ajia", "Asia", "Countries"),
 ("オセアニア", "おせあにあ", "Oseania", "Oceania", "Countries"),
 ("韓国", "かんこく", "Kankoku", "Korea", "Countries"),
 ("中国", "ちゅうごく", "Chūgoku", "China", "Countries"),
 ("インド", "いんど", "Indo", "India", "Countries"),
 ("イタリア", "いたりあ", "Itaria", "Italy", "Countries"),
 ("オーストラリア", "おーすとらりあ", "Ōsutoraria", "Australia", "Countries"),
 ("カナダ", "かなだ", "Kanada", "Canada", "Countries"),
 ("フランス", "ふらんす", "Furansu", "France", "Countries"),
 ("ドイツ", "どいつ", "Doitsu", "Germany", "Countries"),
 ("イギリス", "いぎりす", "Igirisu", "Great Britain", "Countries"),
 ("オランダ", "おらんだ", "Oranda", "Netherlands", "Countries"),
 ("ロシア", "ろしあ", "Roshia", "Russia", "Countries"),
 ("スイス", "すいす", "Suisu", "Switzerland", "Countries"),
 ("地球", "ちきゅう", "chikyū", "globe", "Countries"),
 ("世界", "せかい", "sekai", "world", "Countries"),

 # ----------------------------------------------------------- languages --
 ("英語", "えいご", "Eigo", "English (language)", "Languages"),
 ("フランス語", "ふらんすご", "Furansugo", "French (language)", "Languages"),
 ("ロシア語", "ろしあご", "Roshiago", "Russian (language)", "Languages"),
 ("ドイツ語", "どいつご", "Doitsugo", "German (language)", "Languages"),
 ("イタリア語", "いたりあご", "Itariago", "Italian (language)", "Languages"),
 ("スペイン語", "すぺいんご", "Supeingo", "Spanish (language)", "Languages"),
 ("トルコ語", "とるこご", "Torukogo", "Turkish (language)", "Languages"),
 ("アラビア語", "あらびあご", "Arabiago", "Arabic (language)", "Languages"),

 # -------------------------------------------------------------- music --
 ("ギター", "ぎたー", "gitā", "guitar", "Music"),
 ("琴", "こと", "koto", "koto (long zither)", "Music"),
 ("三味線", "しゃみせん", "shamisen", "shamisen (three-string lute)", "Music"),
 ("バイオリン", "ばいおりん", "baiorin", "violin", "Music"),
 ("尺八", "しゃくはち", "shakuhachi", "shakuhachi (bamboo flute)", "Music"),
 ("踊る", "おどる", "odoru", "to dance", "Music"),
 ("ドラム", "どらむ", "doramu", "drums", "Music"),
 ("トランペット", "とらんぺっと", "toranpetto", "trumpet", "Music"),
 ("ピアノ", "ぴあの", "piano", "piano", "Music"),
 ("フルート", "ふるーと", "furūto", "flute", "Music"),

 # --------------------------------------------------------- transportation --
 ("車", "くるま", "kuruma", "car", "Transportation"),
 ("運転手", "うんてんしゅ", "untenshu", "driver", "Transportation"),
 ("トラック", "とらっく", "torakku", "truck", "Transportation"),
 ("ゴミ収集車", "ごみしゅうしゅうしゃ", "gomi shūshūsha", "garbage truck", "Transportation"),
 ("配送トラック", "はいそうとらっく", "haisō torakku", "delivery van", "Transportation"),
 ("新幹線", "しんかんせん", "shinkansen", "bullet train", "Transportation"),
 ("オートバイ", "おーとばい", "ōtobai", "motorcycle", "Transportation"),
 ("スポーツカー", "すぽーつかー", "supōtsukā", "sports car", "Transportation"),
 ("飛行機で旅行する", "ひこうきでりょこうする", "hikōki de ryokō suru", "to travel by airplane", "Transportation"),
 ("電車で旅行する", "でんしゃでりょこうする", "densha de ryokō suru", "to travel by train", "Transportation"),

 # -------------------------------------------------------- directions --
 ("どこ", "どこ", "doko", "where", "Directions & Position"),
 ("ここ", "ここ", "koko", "here", "Directions & Position"),
 ("そこ", "そこ", "soko", "there", "Directions & Position"),
 ("あそこ", "あそこ", "asoko", "over there", "Directions & Position"),
 ("北", "きた", "kita", "north", "Directions & Position"),
 ("南", "みなみ", "minami", "south", "Directions & Position"),
 ("東", "ひがし", "higashi", "east", "Directions & Position"),
 ("西", "にし", "nishi", "west", "Directions & Position"),
 ("北西", "ほくせい", "hokusei", "northwest", "Directions & Position"),
 ("北東", "ほくとう", "hokutō", "northeast", "Directions & Position"),
 ("南西", "なんせい", "nansei", "southwest", "Directions & Position"),
 ("南東", "なんとう", "nantō", "southeast", "Directions & Position"),
 ("道をたずねる", "みちをたずねる", "michi o tazuneru", "to ask directions", "Directions & Position"),
 ("道を教える", "みちをおしえる", "michi o oshieru", "to give directions", "Directions & Position"),

 # --------------------------------------------------------------- house --
 ("居間", "いま", "ima", "living room", "House & Furniture"),
 ("バルコニー", "ばるこにー", "barukonii", "balcony", "House & Furniture"),
 ("天井", "てんじょう", "tenjō", "ceiling", "House & Furniture"),
 ("鍵", "かぎ", "kagi", "keys", "House & Furniture"),
 ("絵画", "かいが", "kaiga", "painting", "House & Furniture"),
 ("椅子", "いす", "isu", "chair", "House & Furniture"),
 ("壁", "かべ", "kabe", "wall", "House & Furniture"),
 ("テレビ", "てれび", "terebi", "television", "House & Furniture"),
 ("絨毯", "じゅうたん", "jūtan", "carpet", "House & Furniture"),
 ("エアコン", "えあこん", "eakon", "air conditioner", "House & Furniture"),
 ("テーブル", "てーぶる", "tēburu", "table", "House & Furniture"),
 ("ソファ", "そふぁ", "sofa", "sofa", "House & Furniture"),
 ("床", "ゆか", "yuka", "floor", "House & Furniture"),
 ("カーテン", "かーてん", "kāten", "curtain", "House & Furniture"),
 ("窓", "まど", "mado", "window", "House & Furniture"),
 ("枕", "まくら", "makura", "pillow", "House & Furniture"),
 ("ベッド", "べっど", "beddo", "bed", "House & Furniture"),
 ("寝室", "しんしつ", "shinshitsu", "bedroom", "House & Furniture"),
 ("部屋", "へや", "heya", "room", "House & Furniture"),
 ("家", "いえ", "ie", "home, house", "House & Furniture"),
 ("アパート", "あぱーと", "apāto", "apartment", "House & Furniture"),
 ("屋根", "やね", "yane", "roof", "House & Furniture"),
 ("屋根裏", "やねうら", "yaneura", "attic, loft", "House & Furniture"),
 ("地下", "ちか", "chika", "basement, cellar", "House & Furniture"),
 ("車庫", "しゃこ", "shako", "garage", "House & Furniture"),
 ("玄関", "げんかん", "genkan", "entrance", "House & Furniture"),
 ("台所", "だいどころ", "daidokoro", "kitchen", "House & Furniture"),
 ("戸棚", "とだな", "todana", "cabinet", "House & Furniture"),
 ("冷蔵庫", "れいぞうこ", "reizōko", "refrigerator", "House & Furniture"),
 ("オーブン", "おーぶん", "ōbun", "oven", "House & Furniture"),
 ("電子レンジ", "でんしれんじ", "denshi renji", "microwave oven", "House & Furniture"),
 ("やかん", "やかん", "yakan", "kettle", "House & Furniture"),
 ("トースター", "とーすたー", "tōsutā", "toaster", "House & Furniture"),
 ("ストーブ", "すとーぶ", "sutōbu", "stove", "House & Furniture"),
 ("本棚", "ほんだな", "hondana", "bookshelf", "House & Furniture"),
 ("机", "つくえ", "tsukue", "desk", "House & Furniture"),
 ("浴室", "よくしつ", "yokushitsu", "bathroom", "House & Furniture"),
 ("トイレ", "といれ", "toire", "toilet, washroom", "House & Furniture"),
 ("シャワー", "しゃわー", "shawā", "shower", "House & Furniture"),
 ("お風呂", "おふろ", "ofuro", "bathtub", "House & Furniture"),
 ("鉢植え", "はちうえ", "hachiue", "potted plant", "House & Furniture"),
 ("入浴する", "にゅうよくする", "nyūyoku suru", "to bathe", "House & Furniture"),

 # ---------------------------------------------------- family (extended) --
 ("息子", "むすこ", "musuko", "son", "Family & People"),
 ("娘", "むすめ", "musume", "daughter", "Family & People"),
 ("両親", "りょうしん", "ryōshin", "parents", "Family & People"),
 ("妻", "つま", "tsuma", "wife", "Family & People"),
 ("夫", "おっと", "otto", "husband", "Family & People"),
 ("孫", "まご", "mago", "grandson, granddaughter", "Family & People"),
 ("親戚", "しんせき", "shinseki", "relatives", "Family & People"),
 ("隣人", "りんじん", "rinjin", "neighbor", "Family & People"),
 ("家族", "かぞく", "kazoku", "family", "Family & People"),
 ("お父さん", "おとうさん", "otōsan", "father (polite, address form)", "Family & People"),
 ("お母さん", "おかあさん", "okāsan", "mother (polite, address form)", "Family & People"),
 ("お姉さん", "おねえさん", "onēsan", "older sister", "Family & People"),
 ("お兄さん", "おにいさん", "oniisan", "older brother", "Family & People"),
 ("兄弟", "きょうだい", "kyōdai", "brothers", "Family & People"),
 ("姉妹", "しまい", "shimai", "sisters", "Family & People"),
 ("夫婦", "ふうふ", "fūfu", "husband and wife", "Family & People"),
 ("いとこ", "いとこ", "itoko", "cousins", "Family & People"),
 ("甥", "おい", "oi", "nephew", "Family & People"),
 ("姪", "めい", "mei", "niece", "Family & People"),
 ("曾おじいさん", "ひいおじいさん", "hii ojiisan", "great grandfather", "Family & People"),
 ("曾おばあさん", "ひいおばあさん", "hii obāsan", "great grandmother", "Family & People"),

 # -------------------------------------------------------------- Western food --
 ("ホットドッグ", "ほっとどっぐ", "hotto doggu", "hot dog", "Food & Drink"),
 ("サンドイッチ", "さんどいっち", "sandoitchi", "sandwich", "Food & Drink"),
 ("パスタ", "ぱすた", "pasuta", "pasta", "Food & Drink"),
 ("ドーナッツ", "どーなっつ", "dōnattsu", "donuts", "Food & Drink"),
 ("フランスパン", "ふらんすぱん", "furansupan", "baguette", "Food & Drink"),
 ("プリン", "ぷりん", "purin", "pudding", "Food & Drink"),
 ("ラザニア", "らざにあ", "razania", "lasagne", "Food & Drink"),
 ("七面鳥", "しちめんちょう", "shichimenchō", "turkey", "Food & Drink"),
 ("アップルパイ", "あっぷるぱい", "appuru pai", "apple pie", "Food & Drink"),
 ("ハム", "はむ", "hamu", "ham", "Food & Drink"),
 ("サラダ", "さらだ", "sarada", "salad", "Food & Drink"),
 ("ステーキ", "すてーき", "sutēki", "steak", "Food & Drink"),
 ("マッシュポテト", "まっしゅぽてと", "masshu poteto", "mashed potatoes", "Food & Drink"),
 ("ソーセージ", "そーせーじ", "sōsēji", "sausage", "Food & Drink"),

 # ------------------------------------------------------------- drinks --
 ("ミネラルウォーター", "みねらるうぉーたー", "mineraru wōtā", "mineral water", "Food & Drink"),
 ("フルーツジュース", "ふるーつじゅーす", "furūtsu jūsu", "fruit juice", "Food & Drink"),
 ("牛乳", "ぎゅうにゅう", "gyūnyū", "milk", "Food & Drink"),
 ("お茶", "おちゃ", "ocha", "tea", "Food & Drink"),
 ("アイスティー", "あいすてぃー", "aisu tii", "iced tea", "Food & Drink"),
 ("豆乳", "とうにゅう", "tōnyū", "soy milk", "Food & Drink"),
 ("コーラ", "こーら", "kōra", "cola", "Food & Drink"),
 ("水道水", "すいどうすい", "suidōsui", "tap water", "Food & Drink"),
 ("水", "みず", "mizu", "water", "Food & Drink"),
 ("喉が渇いている", "のどがかわいている", "nodo ga kawaite iru", "thirsty", "Food & Drink"),

 # -------------------------------------------------------- japanese food --
 ("定食", "ていしょく", "teishoku", "set menu", "Food & Drink"),
 ("メニュー", "めにゅー", "menyū", "menu", "Food & Drink"),
 ("ご飯", "ごはん", "gohan", "cooked rice", "Food & Drink"),
 ("チャーハン", "ちゃーはん", "chāhan", "fried rice", "Food & Drink"),
 ("箸", "はし", "hashi", "chopsticks", "Food & Drink"),
 ("茶碗", "ちゃわん", "chawan", "rice bowl", "Food & Drink"),
 ("白いご飯", "しろいごはん", "shiroi gohan", "white rice", "Food & Drink"),
 ("皿", "さら", "sara", "plate", "Food & Drink"),
 ("フォーク", "ふぉーく", "fōku", "fork", "Food & Drink"),
 ("ナイフ", "ないふ", "naifu", "knife", "Food & Drink"),
 ("スプーン", "すぷーん", "supūn", "spoon", "Food & Drink"),

 # -------------------------------------------------- market meat/veg/seafood --
 ("豚肉", "ぶたにく", "buta niku", "pork", "Food & Drink"),
 ("ラム", "らむ", "ramu", "lamb, mutton", "Food & Drink"),
 ("鴨肉", "かもにく", "kamo niku", "duck", "Food & Drink"),
 ("鶏肉", "とりにく", "tori niku", "chicken (meat)", "Food & Drink"),
 ("パセリ", "ぱせり", "paseri", "parsley", "Food & Drink"),
 ("魚介類", "ぎょかいるい", "gyokairui", "seafood", "Food & Drink"),
 ("タコ", "たこ", "tako", "octopus", "Food & Drink"),
 ("エビ", "えび", "ebi", "shrimp, prawns", "Food & Drink"),
 ("野菜", "やさい", "yasai", "vegetables", "Food & Drink"),
 ("チンゲン菜", "ちんげんさい", "chingensai", "bok choy", "Food & Drink"),
 ("小松菜", "こまつな", "komatsuna", "Japanese mustard spinach", "Food & Drink"),
 ("ほうれん草", "ほうれんそう", "hōrensō", "spinach", "Food & Drink"),
 ("もやし", "もやし", "moyashi", "bean sprouts", "Food & Drink"),

 # --------------------------------------------------- fruits/nuts/grains --
 ("みかん", "みかん", "mikan", "mandarin orange", "Food & Drink"),
 ("ココナッツ", "ここなっつ", "kokonattsu", "coconut", "Food & Drink"),
 ("パパイヤ", "ぱぱいや", "papaiya", "papaya", "Food & Drink"),
 ("ライム", "らいむ", "raimu", "lime", "Food & Drink"),
 ("ライチ", "らいち", "raichi", "lychee", "Food & Drink"),
 ("マスクメロン", "ますくめろん", "masukumeron", "cantaloupe", "Food & Drink"),
 ("柿", "かき", "kaki", "persimmon", "Food & Drink"),
 ("ピーナッツ", "ぴーなっつ", "piinattsu", "peanuts", "Food & Drink"),
 ("くるみ", "くるみ", "kurumi", "walnuts", "Food & Drink"),
 ("アーモンド", "あーもんど", "āmondo", "almonds", "Food & Drink"),
 ("ピスタチオ", "ぴすたちお", "pisutachio", "pistachios", "Food & Drink"),
 ("栗", "くり", "kuri", "chestnuts", "Food & Drink"),
 ("松の実", "まつのみ", "matsu no mi", "pine nuts", "Food & Drink"),
 ("カシューナッツ", "かしゅーなっつ", "kashū nattsu", "cashew nuts", "Food & Drink"),
 ("ゴマ", "ごま", "goma", "sesame seeds", "Food & Drink"),
 ("大麦", "おおむぎ", "ōmugi", "barley", "Food & Drink"),
 ("そば", "そば", "soba", "buckwheat", "Food & Drink"),
 ("米", "こめ", "kome", "rice (uncooked)", "Food & Drink"),
 ("小麦", "こむぎ", "komugi", "wheat", "Food & Drink"),
 ("穀物", "こくもつ", "kokumotsu", "grains, cereals", "Food & Drink"),
 ("オートミール", "おーとみーる", "ōtomiiru", "oatmeal", "Food & Drink"),
 ("豆", "まめ", "mame", "beans", "Food & Drink"),
 ("とうもろこし", "とうもろこし", "tōmorokoshi", "corn", "Food & Drink"),
 ("小麦粉", "こむぎこ", "komugiko", "flour", "Food & Drink"),
 ("アレルギー", "あれるぎー", "arerugii", "allergy", "Food & Drink"),

 # ------------------------------------------------------------- weather --
 ("レインコート", "れいんこーと", "reinkōto", "raincoat", "Environment & Nature"),
 ("長靴", "ながぐつ", "nagagutsu", "boots", "Environment & Nature"),
 ("晴れた日", "はれたひ", "hareta hi", "clear day", "Environment & Nature"),
 ("曇った日", "くもったひ", "kumotta hi", "cloudy day", "Environment & Nature"),
 ("風が強い", "かぜがつよい", "kaze ga tsuyoi", "windy", "Environment & Nature"),
 ("雨降り", "あめふり", "amefuri", "raining", "Environment & Nature"),
 ("稲妻", "いなずま", "inazuma", "lightning", "Environment & Nature"),
 ("嵐", "あらし", "arashi", "thunderstorm", "Environment & Nature"),
 ("雪が降る", "ゆきがふる", "yuki ga furu", "to snow", "Environment & Nature"),
]

out = []
for word, reading, romaji, meaning, category in PICTURE_DICT:
    out.append({
        "word": word,
        "reading": reading or word,
        "romaji": romaji,
        "meaning": meaning,
        "category": category,
    })

with open("data/picture_dict.json", "w", encoding="utf-8") as f:
    json.dump(out, f, ensure_ascii=False, indent=1)

print(len(out), "picture-dictionary words saved")
from collections import Counter
print(Counter(w["category"] for w in out).most_common())
