import json

# Original multi-turn conversations written for this app (not from any
# uploaded book) covering common everyday situations: work, eating out,
# shopping, travel, small talk, and more. Each line has kanji, hiragana,
# romaji, and English, plus a role label (who's speaking) used for the
# dialogue-bubble display.

def L(role, side, kanji, hiragana, romaji, english):
    return {"role": role, "side": side, "kanji": kanji, "hiragana": hiragana,
            "romaji": romaji, "english": english}


CONVERSATIONS = [

 {
  "id": "self-introduction",
  "title_jp": "自己紹介",
  "title_en": "Introducing Yourself",
  "level": "easy",
  "setting": "Two people meeting for the first time at a party.",
  "lines": [
    L("Tanaka", "A", "はじめまして。田中です。", "はじめまして。たなかです。",
      "Hajimemashite. Tanaka desu.", "Nice to meet you. I'm Tanaka."),
    L("Mike", "B", "はじめまして。私はマイクです。", "はじめまして。わたしはまいくです。",
      "Hajimemashite. Watashi wa Maiku desu.", "Nice to meet you. I'm Mike."),
    L("Tanaka", "A", "どちらから来ましたか。", "どちらからきましたか。",
      "Dochira kara kimashita ka.", "Where are you from?"),
    L("Mike", "B", "アメリカから来ました。", "あめりかからきました。",
      "Amerika kara kimashita.", "I'm from America."),
    L("Tanaka", "A", "お仕事は何ですか。", "おしごとはなんですか。",
      "Oshigoto wa nan desu ka.", "What do you do for work?"),
    L("Mike", "B", "私は教師です。田中さんは？", "わたしはきょうしです。たなかさんは？",
      "Watashi wa kyōshi desu. Tanaka-san wa?", "I'm a teacher. What about you, Tanaka?"),
    L("Tanaka", "A", "私は会社員です。", "わたしはかいしゃいんです。",
      "Watashi wa kaishain desu.", "I'm an office worker."),
    L("Mike", "B", "よろしくお願いします。", "よろしくおねがいします。",
      "Yoroshiku onegaishimasu.", "Pleased to meet you."),
    L("Tanaka", "A", "よろしくお願いします。", "よろしくおねがいします。",
      "Yoroshiku onegaishimasu.", "Pleased to meet you too."),
  ],
  "vocab": [
    {"word": "はじめまして", "reading": "はじめまして", "romaji": "hajimemashite", "meaning": "nice to meet you"},
    {"word": "会社員", "reading": "かいしゃいん", "romaji": "kaishain", "meaning": "office worker"},
    {"word": "教師", "reading": "きょうし", "romaji": "kyōshi", "meaning": "teacher"},
  ],
  "phrases": [
    {"jp": "どちらから来ましたか。", "romaji": "Dochira kara kimashita ka.", "en": "Where are you from?"},
    {"jp": "お仕事は何ですか。", "romaji": "Oshigoto wa nan desu ka.", "en": "What's your job?"},
  ],
 },

 {
  "id": "at-a-cafe",
  "title_jp": "カフェで",
  "title_en": "At a Café",
  "level": "easy",
  "setting": "Ordering a drink at a coffee shop counter.",
  "lines": [
    L("Staff", "A", "いらっしゃいませ。ご注文は？", "いらっしゃいませ。ごちゅうもんは？",
      "Irasshaimase. Gochūmon wa?", "Welcome! What can I get you?"),
    L("Customer", "B", "コーヒーをお願いします。", "こーひーをおねがいします。",
      "Kōhī o onegaishimasu.", "A coffee, please."),
    L("Staff", "A", "サイズはどうしますか。", "さいずはどうしますか。",
      "Saizu wa dō shimasu ka.", "What size would you like?"),
    L("Customer", "B", "Mサイズでお願いします。", "えむさいずでおねがいします。",
      "Emu saizu de onegaishimasu.", "Medium, please."),
    L("Staff", "A", "こちらで召し上がりますか。お持ち帰りですか。", "こちらでめしあがりますか。おもちかえりですか。",
      "Kochira de meshiagarimasu ka. Omochikaeri desu ka.", "For here, or to go?"),
    L("Customer", "B", "こちらで飲みます。", "こちらでのみます。",
      "Kochira de nomimasu.", "I'll drink it here."),
    L("Staff", "A", "少々お待ちください。500円です。", "しょうしょうおまちください。ごひゃくえんです。",
      "Shōshō omachi kudasai. Gohyaku en desu.", "One moment please. That's 500 yen."),
    L("Customer", "B", "はい、どうぞ。", "はい、どうぞ。",
      "Hai, dōzo.", "Here you go."),
  ],
  "vocab": [
    {"word": "注文", "reading": "ちゅうもん", "romaji": "chūmon", "meaning": "order"},
    {"word": "お持ち帰り", "reading": "おもちかえり", "romaji": "omochikaeri", "meaning": "to go, takeout"},
    {"word": "少々お待ちください", "reading": "しょうしょうおまちください", "romaji": "shōshō omachi kudasai", "meaning": "one moment please"},
  ],
  "phrases": [
    {"jp": "こちらで召し上がりますか。お持ち帰りですか。", "romaji": "Kochira de meshiagarimasu ka. Omochikaeri desu ka.", "en": "For here or to go?"},
  ],
 },

 {
  "id": "at-a-restaurant",
  "title_jp": "レストランで",
  "title_en": "At a Restaurant",
  "level": "medium",
  "setting": "A couple is seated and orders their meal.",
  "lines": [
    L("Waiter", "A", "いらっしゃいませ。何名様ですか。", "いらっしゃいませ。なんめいさまですか。",
      "Irasshaimase. Nanmeisama desu ka.", "Welcome! How many people?"),
    L("Customer", "B", "二人です。", "ふたりです。",
      "Futari desu.", "Two, please."),
    L("Waiter", "A", "こちらへどうぞ。ご注文はお決まりですか。", "こちらへどうぞ。ごちゅうもんはおきまりですか。",
      "Kochira e dōzo. Gochūmon wa okimari desu ka.", "This way please. Have you decided on your order?"),
    L("Customer", "B", "すみません、まだです。少し時間をください。", "すみません、まだです。すこしじかんをください。",
      "Sumimasen, mada desu. Sukoshi jikan o kudasai.", "Sorry, not yet. Give us a little time."),
    L("Customer", "B", "すみません、注文をお願いします。", "すみません、ちゅうもんをおねがいします。",
      "Sumimasen, chūmon o onegaishimasu.", "Excuse me, we're ready to order."),
    L("Waiter", "A", "はい、どうぞ。", "はい、どうぞ。",
      "Hai, dōzo.", "Yes, go ahead."),
    L("Customer", "B", "寿司とみそ汁をお願いします。", "すしとみそしるをおねがいします。",
      "Sushi to misoshiru o onegaishimasu.", "Sushi and miso soup, please."),
    L("Waiter", "A", "お飲み物はいかがですか。", "おのみものはいかがですか。",
      "Onomimono wa ikaga desu ka.", "And something to drink?"),
    L("Customer", "B", "お茶をお願いします。", "おちゃをおねがいします。",
      "Ocha o onegaishimasu.", "Tea, please."),
    L("Waiter", "A", "少々お待ちください。", "しょうしょうおまちください。",
      "Shōshō omachi kudasai.", "One moment, please."),
  ],
  "vocab": [
    {"word": "何名様", "reading": "なんめいさま", "romaji": "nanmeisama", "meaning": "how many people (polite)"},
    {"word": "ご注文", "reading": "ごちゅうもん", "romaji": "gochūmon", "meaning": "order (polite)"},
    {"word": "決まる", "reading": "きまる", "romaji": "kimaru", "meaning": "to be decided"},
  ],
  "phrases": [
    {"jp": "ご注文はお決まりですか。", "romaji": "Gochūmon wa okimari desu ka.", "en": "Have you decided on your order?"},
    {"jp": "お飲み物はいかがですか。", "romaji": "Onomimono wa ikaga desu ka.", "en": "Something to drink?"},
  ],
 },

 {
  "id": "asking-directions",
  "title_jp": "道を尋ねる",
  "title_en": "Asking for Directions",
  "level": "medium",
  "setting": "A tourist stops a local to ask how to get to the station.",
  "lines": [
    L("Tourist", "A", "すみません、駅はどこですか。", "すみません、えきはどこですか。",
      "Sumimasen, eki wa doko desu ka.", "Excuse me, where's the station?"),
    L("Local", "B", "駅ですか。この道をまっすぐ行ってください。", "えきですか。このみちをまっすぐいってください。",
      "Eki desu ka. Kono michi o massugu itte kudasai.", "The station? Go straight down this street."),
    L("Tourist", "A", "まっすぐ行って、それから？", "まっすぐいって、それから？",
      "Massugu itte, sorekara?", "Go straight, and then?"),
    L("Local", "B", "二つ目の信号を右に曲がってください。", "ふたつめのしんごうをみぎにまがってください。",
      "Futatsume no shingō o migi ni magatte kudasai.", "Turn right at the second traffic light."),
    L("Tourist", "A", "右に曲がって、それから？", "みぎにまがって、それから？",
      "Migi ni magatte, sorekara?", "Turn right, and then?"),
    L("Local", "B", "駅が左側に見えます。", "えきがひだりがわにみえます。",
      "Eki ga hidarigawa ni miemasu.", "You'll see the station on your left."),
    L("Tourist", "A", "どのくらいかかりますか。", "どのくらいかかりますか。",
      "Dono kurai kakarimasu ka.", "How long does it take?"),
    L("Local", "B", "歩いて十分くらいです。", "あるいてじゅっぷんくらいです。",
      "Aruite juppun kurai desu.", "About ten minutes on foot."),
    L("Tourist", "A", "わかりました。ありがとうございます。", "わかりました。ありがとうございます。",
      "Wakarimashita. Arigatō gozaimasu.", "Got it. Thank you very much."),
    L("Local", "B", "いえいえ、気をつけて。", "いえいえ、きをつけて。",
      "Ie ie, ki o tsukete.", "No problem, take care."),
  ],
  "vocab": [
    {"word": "まっすぐ", "reading": "まっすぐ", "romaji": "massugu", "meaning": "straight ahead"},
    {"word": "信号", "reading": "しんごう", "romaji": "shingō", "meaning": "traffic light"},
    {"word": "曲がる", "reading": "まがる", "romaji": "magaru", "meaning": "to turn"},
    {"word": "左側", "reading": "ひだりがわ", "romaji": "hidarigawa", "meaning": "left side"},
  ],
  "phrases": [
    {"jp": "二つ目の信号を右に曲がってください。", "romaji": "Futatsume no shingō o migi ni magatte kudasai.", "en": "Turn right at the second traffic light."},
    {"jp": "どのくらいかかりますか。", "romaji": "Dono kurai kakarimasu ka.", "en": "How long does it take?"},
  ],
 },

 {
  "id": "work-meeting",
  "title_jp": "会議で",
  "title_en": "In a Meeting",
  "level": "hard",
  "setting": "A team kicks off a project meeting at the office.",
  "lines": [
    L("Tanaka", "A", "会議を始めましょう。", "かいぎをはじめましょう。",
      "Kaigi o hajimemashō.", "Let's start the meeting."),
    L("Suzuki", "B", "はい、資料を配ります。", "はい、しりょうをくばります。",
      "Hai, shiryō o kubarimasu.", "Sure, I'll hand out the materials."),
    L("Tanaka", "A", "今日の議題は新しいプロジェクトです。", "きょうのぎだいはあたらしいぷろじぇくとです。",
      "Kyō no gidai wa atarashii purojekuto desu.", "Today's topic is the new project."),
    L("Suzuki", "B", "いつまでに終わらせますか。", "いつまでにおわらせますか。",
      "Itsu made ni owarasemasu ka.", "By when do we need to finish it?"),
    L("Tanaka", "A", "来月の十五日までにお願いします。", "らいげつのじゅうごにちまでにおねがいします。",
      "Raigetsu no jūgo-nichi made ni onegaishimasu.", "By the 15th of next month, please."),
    L("Suzuki", "B", "分かりました。田中さんは何を担当しますか。", "わかりました。たなかさんはなにをたんとうしますか。",
      "Wakarimashita. Tanaka-san wa nani o tantō shimasu ka.", "Understood. What will you be in charge of, Tanaka?"),
    L("Tanaka", "A", "私はスケジュールを管理します。", "わたしはすけじゅーるをかんりします。",
      "Watashi wa sukejūru o kanri shimasu.", "I'll manage the schedule."),
    L("Suzuki", "B", "では、私はレポートを書きます。", "では、わたしはれぽーとをかきます。",
      "Dewa, watashi wa repōto o kakimasu.", "Then I'll write the report."),
    L("Tanaka", "A", "よろしくお願いします。何か質問はありますか。", "よろしくおねがいします。なにかしつもんはありますか。",
      "Yoroshiku onegaishimasu. Nanika shitsumon wa arimasu ka.", "Thanks. Any questions?"),
    L("Suzuki", "B", "今のところありません。", "いまのところありません。",
      "Ima no tokoro arimasen.", "None at the moment."),
    L("Tanaka", "A", "では、今日の会議はこれで終わります。", "では、きょうのかいぎはこれでおわります。",
      "Dewa, kyō no kaigi wa kore de owarimasu.", "Alright, that's the end of today's meeting."),
  ],
  "vocab": [
    {"word": "議題", "reading": "ぎだい", "romaji": "gidai", "meaning": "agenda topic"},
    {"word": "担当する", "reading": "たんとうする", "romaji": "tantō suru", "meaning": "to be in charge of"},
    {"word": "資料", "reading": "しりょう", "romaji": "shiryō", "meaning": "materials, documents"},
    {"word": "管理する", "reading": "かんりする", "romaji": "kanri suru", "meaning": "to manage"},
  ],
  "phrases": [
    {"jp": "田中さんは何を担当しますか。", "romaji": "Tanaka-san wa nani o tantō shimasu ka.", "en": "What are you in charge of, Tanaka?"},
    {"jp": "今のところありません。", "romaji": "Ima no tokoro arimasen.", "en": "None at the moment."},
  ],
 },

 {
  "id": "calling-in-sick",
  "title_jp": "病気で休む",
  "title_en": "Calling In Sick",
  "level": "medium",
  "setting": "An employee calls their manager to say they can't come to work.",
  "lines": [
    L("Suzuki", "A", "おはようございます、鈴木です。", "おはようございます、すずきです。",
      "Ohayō gozaimasu, Suzuki desu.", "Good morning, this is Suzuki."),
    L("Tanaka", "B", "おはようございます、田中です。", "おはようございます、たなかです。",
      "Ohayō gozaimasu, Tanaka desu.", "Good morning, this is Tanaka."),
    L("Tanaka", "B", "すみません、今日は体調が悪いです。", "すみません、きょうはたいちょうがわるいです。",
      "Sumimasen, kyō wa taichō ga warui desu.", "Sorry, I'm not feeling well today."),
    L("Suzuki", "A", "どうしましたか。", "どうしましたか。",
      "Dō shimashita ka.", "What's wrong?"),
    L("Tanaka", "B", "熱があります。頭も痛いです。", "ねつがあります。あたまもいたいです。",
      "Netsu ga arimasu. Atama mo itai desu.", "I have a fever. My head hurts too."),
    L("Suzuki", "A", "それは大変ですね。今日は休んでください。", "それはたいへんですね。きょうはやすんでください。",
      "Sore wa taihen desu ne. Kyō wa yasunde kudasai.", "That sounds tough. Please rest today."),
    L("Tanaka", "B", "すみません、ご迷惑をかけます。", "すみません、ごめいわくをかけます。",
      "Sumimasen, gomeiwaku o kakemasu.", "I'm sorry for the trouble."),
    L("Suzuki", "A", "いいえ、お大事に。病院に行きましたか。", "いいえ、おだいじに。びょういんにいきましたか。",
      "Iie, odaiji ni. Byōin ni ikimashita ka.", "Not at all, take care. Have you been to the hospital?"),
    L("Tanaka", "B", "これから行きます。", "これからいきます。",
      "Kore kara ikimasu.", "I'm about to go now."),
    L("Suzuki", "A", "わかりました。お休みください。", "わかりました。おやすみください。",
      "Wakarimashita. Oyasumi kudasai.", "Understood. Please rest well."),
  ],
  "vocab": [
    {"word": "体調", "reading": "たいちょう", "romaji": "taichō", "meaning": "physical condition"},
    {"word": "熱", "reading": "ねつ", "romaji": "netsu", "meaning": "fever"},
    {"word": "ご迷惑をかける", "reading": "ごめいわくをかける", "romaji": "gomeiwaku o kakeru", "meaning": "to cause trouble (for someone)"},
    {"word": "お大事に", "reading": "おだいじに", "romaji": "odaiji ni", "meaning": "take care (of yourself)"},
  ],
  "phrases": [
    {"jp": "今日は体調が悪いです。", "romaji": "Kyō wa taichō ga warui desu.", "en": "I'm not feeling well today."},
    {"jp": "今日は休んでください。", "romaji": "Kyō wa yasunde kudasai.", "en": "Please rest today."},
  ],
 },

 {
  "id": "weekend-plans",
  "title_jp": "週末の予定",
  "title_en": "Weekend Plans",
  "level": "easy",
  "setting": "Two coworkers chat about their weekend plans.",
  "lines": [
    L("Yumi", "A", "週末、何をしますか。", "しゅうまつ、なにをしますか。",
      "Shūmatsu, nani o shimasu ka.", "What are you doing this weekend?"),
    L("Ken", "B", "特に予定はありません。田中さんは？", "とくによていはありません。たなかさんは？",
      "Toku ni yotei wa arimasen. Tanaka-san wa?", "No particular plans. What about you?"),
    L("Yumi", "A", "映画を見に行きます。一緒に行きませんか。", "えいがをみにいきます。いっしょにいきませんか。",
      "Eiga o mi ni ikimasu. Issho ni ikimasen ka.", "I'm going to see a movie. Want to come along?"),
    L("Ken", "B", "いいですね。何の映画ですか。", "いいですね。なんのえいがですか。",
      "Ii desu ne. Nan no eiga desu ka.", "Sounds good. What movie?"),
    L("Yumi", "A", "新しいアニメ映画です。", "あたらしいあにめえいがです。",
      "Atarashii anime eiga desu.", "A new animated movie."),
    L("Ken", "B", "何時に会いましょうか。", "なんじにあいましょうか。",
      "Nanji ni aimashō ka.", "What time should we meet?"),
    L("Yumi", "A", "土曜日の三時はどうですか。", "どようびのさんじはどうですか。",
      "Doyōbi no sanji wa dō desu ka.", "How about 3pm on Saturday?"),
    L("Ken", "B", "いいですよ。どこで会いますか。", "いいですよ。どこであいますか。",
      "Ii desu yo. Doko de aimasu ka.", "Sounds good. Where should we meet?"),
    L("Yumi", "A", "駅の前で会いましょう。", "えきのまえであいましょう。",
      "Eki no mae de aimashō.", "Let's meet in front of the station."),
    L("Ken", "B", "わかりました。楽しみです。", "わかりました。たのしみです。",
      "Wakarimashita. Tanoshimi desu.", "Got it. Looking forward to it."),
  ],
  "vocab": [
    {"word": "予定", "reading": "よてい", "romaji": "yotei", "meaning": "plans, schedule"},
    {"word": "特に", "reading": "とくに", "romaji": "tokuni", "meaning": "particularly, especially"},
    {"word": "楽しみ", "reading": "たのしみ", "romaji": "tanoshimi", "meaning": "looking forward to"},
  ],
  "phrases": [
    {"jp": "一緒に行きませんか。", "romaji": "Issho ni ikimasen ka.", "en": "Want to come along?"},
    {"jp": "何時に会いましょうか。", "romaji": "Nanji ni aimashō ka.", "en": "What time should we meet?"},
  ],
 },

 {
  "id": "shopping-for-clothes",
  "title_jp": "洋服を買う",
  "title_en": "Shopping for Clothes",
  "level": "medium",
  "setting": "A customer tries on a shirt at a clothing store.",
  "lines": [
    L("Staff", "A", "いらっしゃいませ。何かお探しですか。", "いらっしゃいませ。なにかおさがしですか。",
      "Irasshaimase. Nanika osagashi desu ka.", "Welcome! Are you looking for something?"),
    L("Customer", "B", "シャツを探しています。", "しゃつをさがしています。",
      "Shatsu o sagashite imasu.", "I'm looking for a shirt."),
    L("Staff", "A", "こちらはいかがですか。", "こちらはいかがですか。",
      "Kochira wa ikaga desu ka.", "How about this one?"),
    L("Customer", "B", "いいですね。試着できますか。", "いいですね。しちゃくできますか。",
      "Ii desu ne. Shichaku dekimasu ka.", "I like it. Can I try it on?"),
    L("Staff", "A", "もちろんです。試着室はこちらです。", "もちろんです。しちゃくしつはこちらです。",
      "Mochiron desu. Shichakushitsu wa kochira desu.", "Of course. The fitting room is this way."),
    L("Customer", "B", "サイズが少し小さいです。もっと大きいサイズはありますか。", "さいずがすこしちいさいです。もっとおおきいさいずはありますか。",
      "Saizu ga sukoshi chiisai desu. Motto ōkii saizu wa arimasu ka.", "The size is a bit small. Do you have a bigger size?"),
    L("Staff", "A", "はい、少々お待ちください。", "はい、しょうしょうおまちください。",
      "Hai, shōshō omachi kudasai.", "Yes, one moment please."),
    L("Customer", "B", "これはいくらですか。", "これはいくらですか。",
      "Kore wa ikura desu ka.", "How much is this?"),
    L("Staff", "A", "三千円です。", "さんぜんえんです。",
      "Sanzen en desu.", "It's 3,000 yen."),
    L("Customer", "B", "これをください。", "これをください。",
      "Kore o kudasai.", "I'll take this one."),
  ],
  "vocab": [
    {"word": "探す", "reading": "さがす", "romaji": "sagasu", "meaning": "to look for"},
    {"word": "試着", "reading": "しちゃく", "romaji": "shichaku", "meaning": "trying on clothes"},
    {"word": "試着室", "reading": "しちゃくしつ", "romaji": "shichakushitsu", "meaning": "fitting room"},
  ],
  "phrases": [
    {"jp": "試着できますか。", "romaji": "Shichaku dekimasu ka.", "en": "Can I try it on?"},
    {"jp": "もっと大きいサイズはありますか。", "romaji": "Motto ōkii saizu wa arimasu ka.", "en": "Do you have a bigger size?"},
  ],
 },

 {
  "id": "at-the-doctor",
  "title_jp": "病院で",
  "title_en": "At the Doctor",
  "level": "hard",
  "setting": "A patient describes their symptoms to a doctor.",
  "lines": [
    L("Doctor", "A", "どうしましたか。", "どうしましたか。",
      "Dō shimashita ka.", "What's the matter?"),
    L("Patient", "B", "三日前から熱があります。", "みっかまえからねつがあります。",
      "Mikka mae kara netsu ga arimasu.", "I've had a fever since three days ago."),
    L("Doctor", "A", "咳は出ますか。", "せきはでますか。",
      "Seki wa demasu ka.", "Do you have a cough?"),
    L("Patient", "B", "はい、咳も出ます。", "はい、せきもでます。",
      "Hai, seki mo demasu.", "Yes, I have a cough too."),
    L("Doctor", "A", "のどを見せてください。", "のどをみせてください。",
      "Nodo o misete kudasai.", "Let me see your throat."),
    L("Patient", "B", "はい。", "はい。",
      "Hai.", "Okay."),
    L("Doctor", "A", "少し赤いですね。風邪でしょう。", "すこしあかいですね。かぜでしょう。",
      "Sukoshi akai desu ne. Kaze deshō.", "It's a bit red. It's probably a cold."),
    L("Patient", "B", "薬をもらえますか。", "くすりをもらえますか。",
      "Kusuri o moraemasu ka.", "Can I get some medicine?"),
    L("Doctor", "A", "はい、三日分出します。一日三回飲んでください。", "はい、みっかぶんだします。いちにちさんかいのんでください。",
      "Hai, mikka-bun dashimasu. Ichinichi sankai nonde kudasai.", "Yes, I'll give you three days' worth. Take it three times a day."),
    L("Patient", "B", "わかりました。ありがとうございます。", "わかりました。ありがとうございます。",
      "Wakarimashita. Arigatō gozaimasu.", "Understood. Thank you."),
  ],
  "vocab": [
    {"word": "咳が出る", "reading": "せきがでる", "romaji": "seki ga deru", "meaning": "to have a cough"},
    {"word": "のど", "reading": "のど", "romaji": "nodo", "meaning": "throat"},
    {"word": "風邪", "reading": "かぜ", "romaji": "kaze", "meaning": "a cold (illness)"},
    {"word": "一日三回", "reading": "いちにちさんかい", "romaji": "ichinichi sankai", "meaning": "three times a day"},
  ],
  "phrases": [
    {"jp": "どうしましたか。", "romaji": "Dō shimashita ka.", "en": "What's the matter?"},
    {"jp": "一日三回飲んでください。", "romaji": "Ichinichi sankai nonde kudasai.", "en": "Take it three times a day."},
  ],
 },

 {
  "id": "hotel-checkin",
  "title_jp": "ホテルで",
  "title_en": "Checking Into a Hotel",
  "level": "medium",
  "setting": "A guest checks in at a hotel front desk.",
  "lines": [
    L("Staff", "A", "いらっしゃいませ。ご予約はありますか。", "いらっしゃいませ。ごよやくはありますか。",
      "Irasshaimase. Goyoyaku wa arimasu ka.", "Welcome! Do you have a reservation?"),
    L("Guest", "B", "はい、田中で予約しました。", "はい、たなかでよやくしました。",
      "Hai, Tanaka de yoyaku shimashita.", "Yes, I booked under the name Tanaka."),
    L("Staff", "A", "少々お待ちください。田中様、二泊のご予約ですね。", "しょうしょうおまちください。たなかさま、にはくのごよやくですね。",
      "Shōshō omachi kudasai. Tanaka-sama, nihaku no goyoyaku desu ne.", "One moment. Mr. Tanaka, a two-night reservation, correct?"),
    L("Guest", "B", "はい、そうです。", "はい、そうです。",
      "Hai, sō desu.", "Yes, that's right."),
    L("Staff", "A", "パスポートを見せてもらえますか。", "ぱすぽーとをみせてもらえますか。",
      "Pasupōto o misete moraemasu ka.", "Could I see your passport?"),
    L("Guest", "B", "はい、どうぞ。", "はい、どうぞ。",
      "Hai, dōzo.", "Yes, here you go."),
    L("Staff", "A", "ありがとうございます。お部屋は五階の501号室です。", "ありがとうございます。おへやはごかいのごーまるいちごうしつです。",
      "Arigatō gozaimasu. Oheya wa gokai no gomaruichi gōshitsu desu.", "Thank you. Your room is 501, on the 5th floor."),
    L("Guest", "B", "チェックアウトは何時ですか。", "ちぇっくあうとはなんじですか。",
      "Chekkuauto wa nanji desu ka.", "What time is checkout?"),
    L("Staff", "A", "十一時です。", "じゅういちじです。",
      "Jūichiji desu.", "It's 11 o'clock."),
    L("Guest", "B", "わかりました。ありがとうございます。", "わかりました。ありがとうございます。",
      "Wakarimashita. Arigatō gozaimasu.", "Got it. Thank you."),
  ],
  "vocab": [
    {"word": "予約", "reading": "よやく", "romaji": "yoyaku", "meaning": "reservation"},
    {"word": "二泊", "reading": "にはく", "romaji": "nihaku", "meaning": "two nights (stay)"},
    {"word": "チェックアウト", "reading": "ちぇっくあうと", "romaji": "chekkuauto", "meaning": "checkout"},
  ],
  "phrases": [
    {"jp": "ご予約はありますか。", "romaji": "Goyoyaku wa arimasu ka.", "en": "Do you have a reservation?"},
    {"jp": "チェックアウトは何時ですか。", "romaji": "Chekkuauto wa nanji desu ka.", "en": "What time is checkout?"},
  ],
 },

 {
  "id": "at-the-station",
  "title_jp": "駅で",
  "title_en": "At the Train Station",
  "level": "easy",
  "setting": "A traveler buys a ticket at the station counter.",
  "lines": [
    L("Traveler", "A", "すみません、新宿までの切符をお願いします。", "すみません、しんじゅくまでのきっぷをおねがいします。",
      "Sumimasen, Shinjuku made no kippu o onegaishimasu.", "Excuse me, a ticket to Shinjuku, please."),
    L("Staff", "B", "片道ですか、往復ですか。", "かたみちですか、おうふくですか。",
      "Katamichi desu ka, ōfuku desu ka.", "One way or round trip?"),
    L("Traveler", "A", "往復でお願いします。", "おうふくでおねがいします。",
      "Ōfuku de onegaishimasu.", "Round trip, please."),
    L("Staff", "B", "480円です。", "よんひゃくはちじゅうえんです。",
      "Yonhyaku hachijū en desu.", "That's 480 yen."),
    L("Traveler", "A", "どのホームですか。", "どのほーむですか。",
      "Dono hōmu desu ka.", "Which platform?"),
    L("Staff", "B", "三番ホームです。", "さんばんほーむです。",
      "Sanban hōmu desu.", "Platform 3."),
    L("Traveler", "A", "何時に出発しますか。", "なんじにしゅっぱつしますか。",
      "Nanji ni shuppatsu shimasu ka.", "What time does it depart?"),
    L("Staff", "B", "十分後に出発します。", "じゅっぷんごにしゅっぱつします。",
      "Juppun-go ni shuppatsu shimasu.", "It departs in ten minutes."),
    L("Traveler", "A", "ありがとうございます。", "ありがとうございます。",
      "Arigatō gozaimasu.", "Thank you."),
  ],
  "vocab": [
    {"word": "切符", "reading": "きっぷ", "romaji": "kippu", "meaning": "ticket"},
    {"word": "片道", "reading": "かたみち", "romaji": "katamichi", "meaning": "one way"},
    {"word": "往復", "reading": "おうふく", "romaji": "ōfuku", "meaning": "round trip"},
    {"word": "ホーム", "reading": "ほーむ", "romaji": "hōmu", "meaning": "platform"},
  ],
  "phrases": [
    {"jp": "片道ですか、往復ですか。", "romaji": "Katamichi desu ka, ōfuku desu ka.", "en": "One way or round trip?"},
    {"jp": "どのホームですか。", "romaji": "Dono hōmu desu ka.", "en": "Which platform?"},
  ],
 },

 {
  "id": "talking-about-hobbies",
  "title_jp": "趣味について",
  "title_en": "Talking About Hobbies",
  "level": "easy",
  "setting": "Two new friends talk about what they like to do.",
  "lines": [
    L("Yumi", "A", "趣味は何ですか。", "しゅみはなんですか。",
      "Shumi wa nan desu ka.", "What's your hobby?"),
    L("Ken", "B", "写真を撮ることです。田中さんは？", "しゃしんをとることです。たなかさんは？",
      "Shashin o toru koto desu. Tanaka-san wa?", "Taking photos. What about you?"),
    L("Yumi", "A", "私は本を読むことです。", "わたしはほんをよむことです。",
      "Watashi wa hon o yomu koto desu.", "Mine is reading books."),
    L("Ken", "B", "どんな本が好きですか。", "どんなほんがすきですか。",
      "Donna hon ga suki desu ka.", "What kind of books do you like?"),
    L("Yumi", "A", "歴史の本が好きです。", "れきしのほんがすきです。",
      "Rekishi no hon ga suki desu.", "I like history books."),
    L("Ken", "B", "私も好きです。よく写真を撮りに旅行します。", "わたしもすきです。よくしゃしんをとりにりょこうします。",
      "Watashi mo suki desu. Yoku shashin o tori ni ryokō shimasu.", "I like that too. I often travel to take photos."),
    L("Yumi", "A", "いいですね。どこへ行きましたか。", "いいですね。どこへいきましたか。",
      "Ii desu ne. Doko e ikimashita ka.", "Nice. Where have you been?"),
    L("Ken", "B", "去年、京都へ行きました。", "きょねん、きょうとへいきました。",
      "Kyonen, Kyōto e ikimashita.", "Last year, I went to Kyoto."),
    L("Yumi", "A", "楽しそうですね。", "たのしそうですね。",
      "Tanoshisō desu ne.", "That sounds fun."),
  ],
  "vocab": [
    {"word": "趣味", "reading": "しゅみ", "romaji": "shumi", "meaning": "hobby"},
    {"word": "歴史", "reading": "れきし", "romaji": "rekishi", "meaning": "history"},
    {"word": "写真を撮る", "reading": "しゃしんをとる", "romaji": "shashin o toru", "meaning": "to take a photo"},
  ],
  "phrases": [
    {"jp": "趣味は何ですか。", "romaji": "Shumi wa nan desu ka.", "en": "What's your hobby?"},
    {"jp": "どんな本が好きですか。", "romaji": "Donna hon ga suki desu ka.", "en": "What kind of books do you like?"},
  ],
 },

 {
  "id": "job-interview",
  "title_jp": "面接",
  "title_en": "A Job Interview",
  "level": "hard",
  "setting": "A candidate is interviewed for a new job.",
  "lines": [
    L("Interviewer", "A", "どうぞお座りください。", "どうぞおすわりください。",
      "Dōzo osuwari kudasai.", "Please, have a seat."),
    L("Candidate", "B", "ありがとうございます。", "ありがとうございます。",
      "Arigatō gozaimasu.", "Thank you."),
    L("Interviewer", "A", "自己紹介をお願いします。", "じこしょうかいをおねがいします。",
      "Jikoshōkai o onegaishimasu.", "Please introduce yourself."),
    L("Candidate", "B", "田中と申します。大学で経済学を勉強しました。", "たなかともうします。だいがくでけいざいがくをべんきょうしました。",
      "Tanaka to mōshimasu. Daigaku de keizaigaku o benkyō shimashita.", "My name is Tanaka. I studied economics at university."),
    L("Interviewer", "A", "どうしてこの会社に興味がありますか。", "どうしてこのかいしゃにきょうみがありますか。",
      "Dōshite kono kaisha ni kyōmi ga arimasu ka.", "Why are you interested in this company?"),
    L("Candidate", "B", "この会社の製品が好きだからです。", "このかいしゃのせいひんがすきだからです。",
      "Kono kaisha no seihin ga suki dakara desu.", "Because I like this company's products."),
    L("Interviewer", "A", "前の仕事で何をしていましたか。", "まえのしごとでなにをしていましたか。",
      "Mae no shigoto de nani o shite imashita ka.", "What did you do at your previous job?"),
    L("Candidate", "B", "マーケティングを担当していました。", "まーけてぃんぐをたんとうしていました。",
      "Māketingu o tantō shite imashita.", "I was in charge of marketing."),
    L("Interviewer", "A", "いつから働けますか。", "いつからはたらけますか。",
      "Itsu kara hatarakemasu ka.", "When can you start working?"),
    L("Candidate", "B", "来月から働けます。", "らいげつからはたらけます。",
      "Raigetsu kara hatarakemasu.", "I can start from next month."),
    L("Interviewer", "A", "ありがとうございます。結果は一週間後にお知らせします。", "ありがとうございます。けっかはいっしゅうかんごにおしらせします。",
      "Arigatō gozaimasu. Kekka wa isshūkan-go ni oshirase shimasu.", "Thank you. We'll let you know the result in a week."),
    L("Candidate", "B", "よろしくお願いします。", "よろしくおねがいします。",
      "Yoroshiku onegaishimasu.", "Thank you, I appreciate it."),
  ],
  "vocab": [
    {"word": "自己紹介", "reading": "じこしょうかい", "romaji": "jikoshōkai", "meaning": "self-introduction"},
    {"word": "興味", "reading": "きょうみ", "romaji": "kyōmi", "meaning": "interest"},
    {"word": "製品", "reading": "せいひん", "romaji": "seihin", "meaning": "product"},
    {"word": "結果", "reading": "けっか", "romaji": "kekka", "meaning": "result"},
  ],
  "phrases": [
    {"jp": "どうしてこの会社に興味がありますか。", "romaji": "Dōshite kono kaisha ni kyōmi ga arimasu ka.", "en": "Why are you interested in this company?"},
    {"jp": "いつから働けますか。", "romaji": "Itsu kara hatarakemasu ka.", "en": "When can you start?"},
  ],
 },

 {
  "id": "apartment-hunting",
  "title_jp": "アパートを探す",
  "title_en": "Apartment Hunting",
  "level": "hard",
  "setting": "A person visits a real estate agent to look for an apartment.",
  "lines": [
    L("Agent", "A", "どんなアパートをお探しですか。", "どんなあぱーとをおさがしですか。",
      "Donna apāto o osagashi desu ka.", "What kind of apartment are you looking for?"),
    L("Customer", "B", "駅から近いアパートを探しています。", "えきからちかいあぱーとをさがしています。",
      "Eki kara chikai apāto o sagashite imasu.", "I'm looking for an apartment close to the station."),
    L("Agent", "A", "家賃はどのくらいをお考えですか。", "やちんはどのくらいをおかんがえですか。",
      "Yachin wa dono kurai o okangae desu ka.", "About how much rent are you thinking of?"),
    L("Customer", "B", "八万円くらいです。", "はちまんえんくらいです。",
      "Hachiman en kurai desu.", "Around 80,000 yen."),
    L("Agent", "A", "こちらはどうですか。駅から五分です。", "こちらはどうですか。えきからごふんです。",
      "Kochira wa dō desu ka. Eki kara gofun desu.", "How about this one? It's five minutes from the station."),
    L("Customer", "B", "いいですね。何階ですか。", "いいですね。なんかいですか。",
      "Ii desu ne. Nankai desu ka.", "Nice. What floor is it on?"),
    L("Agent", "A", "三階です。エレベーターもあります。", "さんかいです。えれべーたーもあります。",
      "Sankai desu. Erebētā mo arimasu.", "The third floor. There's also an elevator."),
    L("Customer", "B", "見学できますか。", "けんがくできますか。",
      "Kengaku dekimasu ka.", "Can I take a look at it?"),
    L("Agent", "A", "もちろんです。明日はどうですか。", "もちろんです。あしたはどうですか。",
      "Mochiron desu. Ashita wa dō desu ka.", "Of course. How about tomorrow?"),
    L("Customer", "B", "はい、大丈夫です。", "はい、だいじょうぶです。",
      "Hai, daijōbu desu.", "Yes, that works."),
  ],
  "vocab": [
    {"word": "家賃", "reading": "やちん", "romaji": "yachin", "meaning": "rent"},
    {"word": "見学", "reading": "けんがく", "romaji": "kengaku", "meaning": "viewing, tour"},
    {"word": "エレベーター", "reading": "えれべーたー", "romaji": "erebētā", "meaning": "elevator"},
  ],
  "phrases": [
    {"jp": "家賃はどのくらいをお考えですか。", "romaji": "Yachin wa dono kurai o okangae desu ka.", "en": "About how much rent are you thinking?"},
    {"jp": "見学できますか。", "romaji": "Kengaku dekimasu ka.", "en": "Can I take a look at it?"},
  ],
 },

 {
  "id": "at-the-supermarket",
  "title_jp": "スーパーで",
  "title_en": "At the Supermarket",
  "level": "easy",
  "setting": "A shopper asks where to find something and checks out.",
  "lines": [
    L("Customer", "A", "すみません、卵はどこにありますか。", "すみません、たまごはどこにありますか。",
      "Sumimasen, tamago wa doko ni arimasu ka.", "Excuse me, where are the eggs?"),
    L("Staff", "B", "あちらの冷蔵庫にあります。", "あちらのれいぞうこにあります。",
      "Achira no reizōko ni arimasu.", "They're in the refrigerator over there."),
    L("Customer", "A", "ありがとうございます。牛乳もありますか。", "ありがとうございます。ぎゅうにゅうもありますか。",
      "Arigatō gozaimasu. Gyūnyū mo arimasu ka.", "Thanks. Is there milk too?"),
    L("Staff", "B", "はい、同じところにあります。", "はい、おなじところにあります。",
      "Hai, onaji tokoro ni arimasu.", "Yes, it's in the same place."),
    L("Cashier", "B", "袋は要りますか。", "ふくろはいりますか。",
      "Fukuro wa irimasu ka.", "Do you need a bag?"),
    L("Customer", "A", "いいえ、大丈夫です。マイバッグがあります。", "いいえ、だいじょうぶです。まいばっぐがあります。",
      "Iie, daijōbu desu. Mai baggu ga arimasu.", "No, I'm fine. I have my own bag."),
    L("Cashier", "B", "合計で千二百円です。", "ごうけいでせんにひゃくえんです。",
      "Gōkei de sen ni hyaku en desu.", "That's 1,200 yen in total."),
    L("Customer", "A", "カードで払えますか。", "かーどではらえますか。",
      "Kādo de haraemasu ka.", "Can I pay by card?"),
    L("Cashier", "B", "はい、大丈夫です。", "はい、だいじょうぶです。",
      "Hai, daijōbu desu.", "Yes, that's fine."),
  ],
  "vocab": [
    {"word": "冷蔵庫", "reading": "れいぞうこ", "romaji": "reizōko", "meaning": "refrigerator"},
    {"word": "袋", "reading": "ふくろ", "romaji": "fukuro", "meaning": "bag"},
    {"word": "合計", "reading": "ごうけい", "romaji": "gōkei", "meaning": "total"},
  ],
  "phrases": [
    {"jp": "袋は要りますか。", "romaji": "Fukuro wa irimasu ka.", "en": "Do you need a bag?"},
    {"jp": "カードで払えますか。", "romaji": "Kādo de haraemasu ka.", "en": "Can I pay by card?"},
  ],
 },

 {
  "id": "weather-smalltalk",
  "title_jp": "天気について",
  "title_en": "Small Talk About the Weather",
  "level": "easy",
  "setting": "Two neighbors chat briefly about the cold weather.",
  "lines": [
    L("Yumi", "A", "今日は寒いですね。", "きょうはさむいですね。",
      "Kyō wa samui desu ne.", "It's cold today, isn't it."),
    L("Ken", "B", "そうですね。明日はもっと寒くなるそうです。", "そうですね。あしたはもっとさむくなるそうです。",
      "Sō desu ne. Ashita wa motto samuku naru sō desu.", "It sure is. I heard it'll get even colder tomorrow."),
    L("Yumi", "A", "雪が降りますか。", "ゆきがふりますか。",
      "Yuki ga furimasu ka.", "Will it snow?"),
    L("Ken", "B", "天気予報では降るかもしれません。", "てんきよほうではふるかもしれません。",
      "Tenki yohō de wa furu kamoshiremasen.", "The weather forecast says it might."),
    L("Yumi", "A", "傘を持って行った方がいいですか。", "かさをもっていったほうがいいですか。",
      "Kasa o motte itta hō ga ii desu ka.", "Should I bring an umbrella?"),
    L("Ken", "B", "いいえ、傘より暖かい服がいいですよ。", "いいえ、かさよりあたたかいふくがいいですよ。",
      "Iie, kasa yori atatakai fuku ga ii desu yo.", "No, warm clothes are better than an umbrella."),
    L("Yumi", "A", "そうですね。ありがとうございます。", "そうですね。ありがとうございます。",
      "Sō desu ne. Arigatō gozaimasu.", "You're right. Thanks."),
  ],
  "vocab": [
    {"word": "天気予報", "reading": "てんきよほう", "romaji": "tenki yohō", "meaning": "weather forecast"},
    {"word": "かもしれません", "reading": "かもしれません", "romaji": "kamoshiremasen", "meaning": "might, perhaps"},
    {"word": "暖かい", "reading": "あたたかい", "romaji": "atatakai", "meaning": "warm"},
  ],
  "phrases": [
    {"jp": "傘を持って行った方がいいですか。", "romaji": "Kasa o motte itta hō ga ii desu ka.", "en": "Should I bring an umbrella?"},
  ],
 },

 {
  "id": "talking-about-family",
  "title_jp": "家族について",
  "title_en": "Talking About Family",
  "level": "easy",
  "setting": "Two friends talk about their siblings and parents.",
  "lines": [
    L("Ken", "A", "兄弟はいますか。", "きょうだいはいますか。",
      "Kyōdai wa imasu ka.", "Do you have any siblings?"),
    L("Yumi", "B", "はい、姉が一人います。田中さんは？", "はい、あねがひとりいます。たなかさんは？",
      "Hai, ane ga hitori imasu. Tanaka-san wa?", "Yes, I have one older sister. What about you?"),
    L("Ken", "A", "私は一人っ子です。", "わたしはひとりっこです。",
      "Watashi wa hitorikko desu.", "I'm an only child."),
    L("Yumi", "B", "そうですか。ご両親はどこに住んでいますか。", "そうですか。ごりょうしんはどこにすんでいますか。",
      "Sō desu ka. Goryōshin wa doko ni sunde imasu ka.", "I see. Where do your parents live?"),
    L("Ken", "A", "大阪に住んでいます。", "おおさかにすんでいます。",
      "Ōsaka ni sunde imasu.", "They live in Osaka."),
    L("Yumi", "B", "私の両親も大阪です！", "わたしのりょうしんもおおさかです！",
      "Watashi no ryōshin mo Ōsaka desu!", "My parents are in Osaka too!"),
    L("Ken", "A", "本当ですか。近いですね。", "ほんとうですか。ちかいですね。",
      "Hontō desu ka. Chikai desu ne.", "Really? What a small world."),
  ],
  "vocab": [
    {"word": "一人っ子", "reading": "ひとりっこ", "romaji": "hitorikko", "meaning": "only child"},
    {"word": "ご両親", "reading": "ごりょうしん", "romaji": "goryōshin", "meaning": "parents (polite)"},
  ],
  "phrases": [
    {"jp": "兄弟はいますか。", "romaji": "Kyōdai wa imasu ka.", "en": "Do you have any siblings?"},
  ],
 },

 {
  "id": "travel-planning",
  "title_jp": "旅行の計画",
  "title_en": "Planning a Trip",
  "level": "medium",
  "setting": "Two friends discuss summer vacation travel plans.",
  "lines": [
    L("Yumi", "A", "夏休みにどこか行きますか。", "なつやすみにどこかいきますか。",
      "Natsuyasumi ni dokoka ikimasu ka.", "Are you going anywhere this summer vacation?"),
    L("Ken", "B", "沖縄に行きたいです。", "おきなわにいきたいです。",
      "Okinawa ni ikitai desu.", "I want to go to Okinawa."),
    L("Yumi", "A", "いいですね。飛行機で行きますか。", "いいですね。ひこうきでいきますか。",
      "Ii desu ne. Hikōki de ikimasu ka.", "Nice. Are you going by plane?"),
    L("Ken", "B", "はい、飛行機を予約しました。", "はい、ひこうきをよやくしました。",
      "Hai, hikōki o yoyaku shimashita.", "Yes, I booked a flight."),
    L("Yumi", "A", "ホテルは決めましたか。", "ほてるはきめましたか。",
      "Hoteru wa kimemashita ka.", "Have you decided on a hotel?"),
    L("Ken", "B", "まだです。おすすめはありますか。", "まだです。おすすめはありますか。",
      "Mada desu. Osusume wa arimasu ka.", "Not yet. Any recommendations?"),
    L("Yumi", "A", "海の近いホテルがいいですよ。", "うみのちかいほてるがいいですよ。",
      "Umi no chikai hoteru ga ii desu yo.", "A hotel near the ocean is good."),
    L("Ken", "B", "そうします。ありがとうございます。", "そうします。ありがとうございます。",
      "Sō shimasu. Arigatō gozaimasu.", "I'll do that. Thanks."),
  ],
  "vocab": [
    {"word": "予約する", "reading": "よやくする", "romaji": "yoyaku suru", "meaning": "to book, reserve"},
    {"word": "おすすめ", "reading": "おすすめ", "romaji": "osusume", "meaning": "recommendation"},
  ],
  "phrases": [
    {"jp": "ホテルは決めましたか。", "romaji": "Hoteru wa kimemashita ka.", "en": "Have you decided on a hotel?"},
  ],
 },

 {
  "id": "asking-for-help",
  "title_jp": "手伝いをお願いする",
  "title_en": "Asking for Help",
  "level": "easy",
  "setting": "Someone asks a coworker to help carry something heavy.",
  "lines": [
    L("Yumi", "A", "すみません、ちょっと手伝ってもらえますか。", "すみません、ちょっとてつだってもらえますか。",
      "Sumimasen, chotto tetsudatte moraemasu ka.", "Excuse me, could you help me for a moment?"),
    L("Ken", "B", "もちろんです。何ですか。", "もちろんです。なんですか。",
      "Mochiron desu. Nan desu ka.", "Of course. What is it?"),
    L("Yumi", "A", "この箱を運んでもらえますか。重いです。", "このはこをはこんでもらえますか。おもいです。",
      "Kono hako o hakonde moraemasu ka. Omoi desu.", "Could you carry this box? It's heavy."),
    L("Ken", "B", "いいですよ。どこに運びますか。", "いいですよ。どこにはこびますか。",
      "Ii desu yo. Doko ni hakobimasu ka.", "Sure. Where should I take it?"),
    L("Yumi", "A", "あちらの部屋までお願いします。", "あちらのへやまでおねがいします。",
      "Achira no heya made onegaishimasu.", "To that room over there, please."),
    L("Ken", "B", "わかりました。", "わかりました。",
      "Wakarimashita.", "Got it."),
    L("Yumi", "A", "本当にありがとうございます。", "ほんとうにありがとうございます。",
      "Hontō ni arigatō gozaimasu.", "Thank you so much."),
    L("Ken", "B", "いえいえ、大丈夫です。", "いえいえ、だいじょうぶです。",
      "Ie ie, daijōbu desu.", "No problem at all."),
  ],
  "vocab": [
    {"word": "手伝う", "reading": "てつだう", "romaji": "tetsudau", "meaning": "to help"},
    {"word": "運ぶ", "reading": "はこぶ", "romaji": "hakobu", "meaning": "to carry"},
    {"word": "重い", "reading": "おもい", "romaji": "omoi", "meaning": "heavy"},
  ],
  "phrases": [
    {"jp": "ちょっと手伝ってもらえますか。", "romaji": "Chotto tetsudatte moraemasu ka.", "en": "Could you help me for a moment?"},
  ],
 },

 {
  "id": "reporting-a-problem",
  "title_jp": "故障の相談",
  "title_en": "Reporting a Problem",
  "level": "medium",
  "setting": "A hotel guest reports that the air conditioner is broken.",
  "lines": [
    L("Guest", "A", "すみません、エアコンが壊れています。", "すみません、えあこんがこわれています。",
      "Sumimasen, eakon ga kowarete imasu.", "Excuse me, the air conditioner is broken."),
    L("Staff", "B", "申し訳ございません。すぐに確認します。", "もうしわけございません。すぐにかくにんします。",
      "Mōshiwake gozaimasen. Sugu ni kakunin shimasu.", "I'm very sorry. I'll check right away."),
    L("Guest", "A", "部屋がとても暑いです。", "へやがとてもあついです。",
      "Heya ga totemo atsui desu.", "The room is very hot."),
    L("Staff", "B", "別の部屋をご用意できます。", "べつのへやをごよういできます。",
      "Betsu no heya o goyōi dekimasu.", "We can prepare a different room for you."),
    L("Guest", "A", "それはありがたいです。", "それはありがたいです。",
      "Sore wa arigatai desu.", "That would be great."),
    L("Staff", "B", "少々お待ちください。荷物はそのままで大丈夫です。", "しょうしょうおまちください。にもつはそのままでだいじょうぶです。",
      "Shōshō omachi kudasai. Nimotsu wa sono mama de daijōbu desu.", "One moment please. You can leave your luggage as it is."),
    L("Guest", "A", "わかりました。よろしくお願いします。", "わかりました。よろしくおねがいします。",
      "Wakarimashita. Yoroshiku onegaishimasu.", "Understood. Thank you for taking care of it."),
  ],
  "vocab": [
    {"word": "壊れる", "reading": "こわれる", "romaji": "kowareru", "meaning": "to break, be broken"},
    {"word": "確認する", "reading": "かくにんする", "romaji": "kakunin suru", "meaning": "to check, confirm"},
    {"word": "用意する", "reading": "よういする", "romaji": "yōi suru", "meaning": "to prepare"},
  ],
  "phrases": [
    {"jp": "エアコンが壊れています。", "romaji": "Eakon ga kowarete imasu.", "en": "The air conditioner is broken."},
    {"jp": "申し訳ございません。", "romaji": "Mōshiwake gozaimasen.", "en": "I'm very sorry (formal apology)."},
  ],
 },
]

with open("data/conversations.json", "w", encoding="utf-8") as f:
    json.dump(CONVERSATIONS, f, ensure_ascii=False, indent=1)

print(len(CONVERSATIONS), "conversations written")
for c in CONVERSATIONS:
    print(" ", c["id"], "-", c["level"], "-", len(c["lines"]), "lines")
